package seremis.geninfusion.api.soul.lib

/**
 * This is a library class containing all variable names used in reflection.
 * The variables in this class will be automatically converted to srg names
 * by the build script.
 */
object VariableLib {

    var obfuscated = false

    final val EntityIsJumping = "isJumping"
    final val EntityMoveStrafing = "moveStrafing"
    final val EntityMoveForward = "moveForward"
    final val EntityRandomYawVelocity = "randomYawVelocity"
    final val EntityRotationYawHead = "rotationYawHead"
    final val EntityRotationYaw = "rotationYaw"
    final val EntityRotationPitch = "rotationPitch"
    final val EntityFleeingTick = "fleeingTick"
    final val EntityHasAttacked = "hasAttacked"
    final val EntityEntityToAttack = "entityToAttack"
    final val EntityPathToEntity = "pathToEntity"
    final val EntityEntityAge = "entityAge"
    final val EntityInWater = "inWater"
    final val EntityWidth = "width"
    final val EntityHeight = "height"
    final val EntityPosX = "posX"
    final val EntityPosY = "posY"
    final val EntityPosZ = "posZ"
    final val EntityPrevPosX = "prevPosX"
    final val EntityPrevPosY = "prevPosY"
    final val EntityPrevPosZ = "prevPosZ"
    final val EntityMotionX = "motionX"
    final val EntityMotionY = "motionY"
    final val EntityMotionZ = "motionZ"
    final val EntityIsCollidedHorizontally = "isCollidedHorizontally"
    final val EntityIsCollidedVertically = "isCollidedVertically"
    final val EntityCurrentTarget = "currentTarget"
    final val EntityNumTicksToChaseTarget = "numTicksToChaseTarget"
    final val EntityDefaultPitch = "defaultPitch"
    final val EntityPossibleAnimations = "possibleAnimations"
    final val EntityActiveAnimations = "activeAnimations"
    final val EntityPendingAnimations = "pendingAnimations"
    final val EntityAttackTime = "attackTime"
    final val EntityHurtTime = "hurtTime"
    final val EntityMaxHurtTime = "maxHurtTime"
    final val EntityHurtResistantTime = "hurtResistantTime"
    final val EntityMaxHurtResistantTime = "maxHurtResistantTime"
    final val EntityRecentlyHit = "recentlyHit"
    final val EntityTicksExisted = "ticksExisted"
    final val EntityLastAttacker = "lastAttacker"
    final val EntityEntityLivingToAttack = "entityLivingToAttack"
    final val EntityAttackingPlayer = "attackingPlayer"
    final val EntityInvulnerable = "invulnerable"
    final val EntityRevengeTimer = "revengeTimer"
    final val EntityLimbSwingAmount = "limbSwingAmount"
    final val EntityLastDamage = "lastDamage"
    final val EntityPrevHealth = "prevHealth"
    final val EntityAttackedAtYaw = "attackedAtYaw"
    final val EntityScoreValue = "scoreValue"
    final val EntityDead = "dead"
    final val EntityFuseState = "fuseState"
    final val EntityCharged = "charged"
    final val EntityIgnited = "ignited"
    final val EntityExplosionRadius = "explosionRadius"
    final val EntityFuseTime = "fuseTime"
    final val EntityTimeSinceIgnited = "timeSinceIgnited"
    final val EntityIsImmuneToFire = "isImmuneToFire"
    final val EntityFire = "fire"
    final val EntityFallDistance = "fallDistance"
    final val EntityIsDead = "isDead"
    final val EntityMaximumHomeDistance = "maximumHomeDistance"
    final val EntityHomePosition = "homePosition"
    final val EntityHealth = "health"
    final val EntityCreatureAttribute = "creatureAttribute"
    final val EntityExperienceValue = "experienceValue"
    final val EntityEquipmentDropChances = "equipmentDropChances"
    final val EntityAIEnabled = "aiEnabled"
    final val EntityCaptureDrops = "captureDrops"
    final val EntityCapturedDrops = "capturedDrops"
    final val EntityEquipment = "equipment"
    final val EntityPersistenceRequired = "persistenceRequired"
    final val EntityPreviousEquipment = "previousEquipment"
    final val EntityPortalCounter = "portalCounter"
    final val EntityInPortal = "inPortal"
    final val EntityPrevMovedDistance = "field_70763_ax"
    final val EntityMovedDistance = "field_70764_aw"
    final val EntityJumpTick = "jumpTick"
    final val EntityNewPosRotationIncrements = "newPosRotationIncrements"
    final val EntityNewPosX = "newPosX"
    final val EntityNewPosY = "newPosY"
    final val EntityNewPosZ = "newPosZ"
    final val EntityNewRotationYaw = "newRotationYaw"
    final val EntityNewRotationPitch = "newRotationPitch"
    final val EntityPrevOnGroundSpeedFactor = "field_70768_au"
    final val EntityOnGroundSpeedFactor = "field_110154_aX"
    final val EntityLivingSoundTime = "livingSoundTime"
    final val EntityTalkInterval = "talkInterval"
    final val EntityPartialTickTime = "partialTickTime"
    final val DataWatcherNameTag = "nameTag"
    final val ModelRendererBoxName = "boxName"
    final val ModelRendererTextureOffsetX = "textureOffsetX"
    final val ModelRendererTextureOffsetY = "textureOffsetY"
    final val ModelRendererBaseModel = "baseModel"
    final val ModelRendererDisplayList = "displayList"
    final val ModelRendererCompiled = "compiled"
    final val ModelBoxQuadList = "quadList"
    final val ModelBoxVertexPositions = "vertexPositions"
    final val ModelBipedEars = "bipedEars"
    final val ModelBipedCloak = "bipedCloak"
    final val ModelBipedHeadwear = "bipedHeadwear"
}
