package seremis.geninfusion.soul.gene

import seremis.geninfusion.api.lib.Genes
import seremis.geninfusion.soul.MasterGene

class GeneUseNewAI extends MasterGene(classOf[Boolean]) {
    addControlledGene(Genes.GeneAIArrowAttack)
    addControlledGene(Genes.GeneAIAttackOnCollide)
    addControlledGene(Genes.GeneAIAvoidEntity)
    addControlledGene(Genes.GeneAIBeg)
    addControlledGene(Genes.GeneAIBreakDoor)
    addControlledGene(Genes.GeneAIControlledByPlayer)
    addControlledGene(Genes.GeneAICreeperSwell)
    addControlledGene(Genes.GeneAIDefendVillage)
    addControlledGene(Genes.GeneAIEatGrass)
    addControlledGene(Genes.GeneAIFleeSun)
    addControlledGene(Genes.GeneAIFollowGolem)
    addControlledGene(Genes.GeneAIFollowOwner)
    addControlledGene(Genes.GeneAIFollowParent)
    addControlledGene(Genes.GeneAIHurtByTarget)
    addControlledGene(Genes.GeneAILeapAtTarget)
    addControlledGene(Genes.GeneAILookAtTradePlayer)
    addControlledGene(Genes.GeneAILookAtVillager)
    addControlledGene(Genes.GeneAILookIdle)
    addControlledGene(Genes.GeneAIMate)
    addControlledGene(Genes.GeneAIMoveIndoors)
    addControlledGene(Genes.GeneAIMoveThroughVillage)
    addControlledGene(Genes.GeneAIMoveTowardsRestriction)
    addControlledGene(Genes.GeneAIMoveTowardsTarget)
    addControlledGene(Genes.GeneAINearestAttackableTarget)
    addControlledGene(Genes.GeneAIOcelotAttack)
    addControlledGene(Genes.GeneAIOcelotSit)
    addControlledGene(Genes.GeneAIOpenDoor)
    addControlledGene(Genes.GeneAIOwnerHurtByTarget)
    addControlledGene(Genes.GeneAIOwnerHurtTarget)
    addControlledGene(Genes.GeneAIPanic)
    addControlledGene(Genes.GeneAIPlay)
    addControlledGene(Genes.GeneAIRestrictOpenDoor)
    addControlledGene(Genes.GeneAIRestrictSun)
    addControlledGene(Genes.GeneAIRunAroundLikeCrazy)
    addControlledGene(Genes.GeneAISit)
    addControlledGene(Genes.GeneAISwimming)
    addControlledGene(Genes.GeneAITargetNonTamed)
    addControlledGene(Genes.GeneAITempt)
    addControlledGene(Genes.GeneAITradePlayer)
    addControlledGene(Genes.GeneAIVillagerMate)
    addControlledGene(Genes.GeneAIWander)
    addControlledGene(Genes.GeneAIWatchClosest)
    addControlledGene(Genes.GeneAIWatchClosest2)
}
