package com.seremis.geninfusion.api.lib

import java.{lang, util}
import java.util.UUID

import com.seremis.geninfusion.api.util.TypedName
import com.seremis.geninfusion.util.MCPNames._
import net.minecraft.block.material.EnumPushReaction
import net.minecraft.command.CommandResultStats
import net.minecraft.entity.Entity
import net.minecraft.entity.item.EntityItem
import net.minecraft.item.ItemStack
import net.minecraft.nbt.NBTTagList
import net.minecraft.network.datasync.EntityDataManager
import net.minecraft.scoreboard.Team
import net.minecraft.server.MinecraftServer
import net.minecraft.util.math.{AxisAlignedBB, BlockPos, RayTraceResult, Vec3d}
import net.minecraft.util.text.ITextComponent
import net.minecraft.util.text.event.HoverEvent
import net.minecraft.util.{EnumActionResult, EnumFacing, SoundCategory, SoundEvent}
import net.minecraft.world.World

object FunctionLib {
    final val FuncEntityGetEntityId = TypedName(method("func_145782_y"), classOf[Int])
    final val FuncEntitySetEntityId = TypedName(method("func_145769_d"), classOf[Unit])
    final val FuncEntityGetTags = TypedName(method("func_184216_O"), classOf[util.Set[String]])
    final val FuncEntityAddTag = TypedName(method("func_184211_a"), classOf[Boolean])
    final val FuncEntityRemoveTag = TypedName(method("func_184197_b"), classOf[Boolean])
    final val FuncEntityOnKillCommand = TypedName(method("func_174812_G"), classOf[Unit])
    final val FuncEntityEntityInit = TypedName(method("func_70088_a"), classOf[Unit])
    final val FuncEntityGetDataManager = TypedName(method("func_184212_Q"), classOf[EntityDataManager])
    final val FuncEntityEquals = TypedName("equals", classOf[Boolean])
    final val FuncEntityHashCode = TypedName("hashCode", classOf[Int])
    final val FuncEntityPreparePlayerToSpawn = TypedName(method("func_70065_x"), classOf[Unit])
    final val FuncEntitySetDead = TypedName(method("func_70106_y"), classOf[Unit])
    final val FuncEntitySetDropItemsWhenDead = TypedName(method("func_184174_b"), classOf[Unit])
    final val FuncEntitySetSize = TypedName(method("func_70105_a"), classOf[Unit])
    final val FuncEntitySetRotation = TypedName(method("func_70101_b"), classOf[Unit])
    final val FuncEntitySetPosition = TypedName(method("func_70107_b"), classOf[Unit])
    final val FuncEntitySetAngles = TypedName(method("func_70082_c"), classOf[Unit])
    final val FuncEntityOnUpdate = TypedName(method("func_70071_h_"), classOf[Unit])
    final val FuncEntityOnEntityUpdate = TypedName(method("func_70030_z"), classOf[Unit])
    final val FuncEntityDecrementTimeUntilPortal = TypedName(method("func_184173_H"), classOf[Unit])
    final val FuncEntityGetMaxInPortalTime = TypedName(method("func_82145_z"), classOf[Int])
    final val FuncEntitySetOnFireFromLava = TypedName(method("func_70044_A"), classOf[Unit])
    final val FuncEntitySetFire = TypedName(method("func_70015_d"), classOf[Unit])
    final val FuncEntityExtinguish = TypedName(method("func_70066_B"), classOf[Unit])
    final val FuncEntityKill = TypedName(method("func_70076_C"), classOf[Unit])
    final val FuncEntityIsOffsetPositionInLiquid = TypedName(method("func_70038_c"), classOf[Boolean])
    final val FuncEntityIsLiquidPresentInAABB = TypedName(method("func_174809_b"), classOf[Boolean])
    final val FuncEntityMoveEntity = TypedName(method("func_70091_d"), classOf[Unit])
    final val FuncEntityResetPositionToBB = TypedName(method("func_174829_m"), classOf[Unit])
    final val FuncEntityGetSwimSound = TypedName(method("func_184184_Z"), classOf[SoundEvent])
    final val FuncEntityGetSplashSound = TypedName(method("func_184181_aa"), classOf[SoundEvent])
    final val FuncEntityDoBlockCollisions = TypedName(method("func_145775_I"), classOf[Unit])
    final val FuncEntityPlayStepSound = TypedName(method("func_180429_a"), classOf[Unit])
    final val FuncEntityPlaySound = TypedName(method("func_184185_a"), classOf[Unit])
    final val FuncEntityIsSilent = TypedName(method("func_174814_R"), classOf[Boolean])
    final val FuncEntitySetSilent = TypedName(method("func_174810_b"), classOf[Unit])
    final val FuncEntityCanTriggerWalking = TypedName(method("func_70041_e_"), classOf[Boolean])
    final val FuncEntityUpdateFallState = TypedName(method("func_184231_a"), classOf[Unit])
    final val FuncEntityGetCollisionBoundingBox = TypedName(method("func_70046_E"), classOf[AxisAlignedBB])
    final val FuncEntityDealFireDamage = TypedName(method("func_70081_e"), classOf[Unit])
    final val FuncEntityIsImmuneToFire = TypedName(method("func_70045_F"), classOf[Boolean])
    final val FuncEntityFall = TypedName(method("func_180430_e"), classOf[Unit])
    final val FuncEntityIsWet = TypedName(method("func_70026_G"), classOf[Boolean])
    final val FuncEntityIsInWater = TypedName(method("func_70090_H"), classOf[Boolean])
    final val FuncEntityHandleWaterMovement = TypedName(method("func_70072_I"), classOf[Boolean])
    final val FuncEntityResetHeight = TypedName(method("func_71061_d_"), classOf[Unit])
    final val FuncEntitySpawnRunningParticles = TypedName(method("func_174830_Y"), classOf[Unit])
    final val FuncEntityCreateRunningParticles = TypedName(method("func_174808_Z"), classOf[Unit])
    final val FuncEntityIsInsideOfMaterial = TypedName(method("func_70055_a"), classOf[Boolean])
    final val FuncEntityIsInLava = TypedName(method("func_180799_ab"), classOf[Boolean])
    final val FuncEntityMoveFlying = TypedName(method("func_70060_a"), classOf[Unit])
    final val FuncEntityGetBrightnessForRender = TypedName(method("func_70070_b"), classOf[Int])
    final val FuncEntityGetBrightness = TypedName(method("func_70013_c"), classOf[Float])
    final val FuncEntitySetWorld = TypedName(method("func_70029_a"), classOf[Unit])
    final val FuncEntitySetPositionAndRotation = TypedName(method("func_70080_a"), classOf[Unit])
    final val FuncEntityMoveToBlockPosAndAngles = TypedName(method("func_174828_a"), classOf[Unit])
    final val FuncEntitySetLocationAndAngles = TypedName(method("func_70012_b"), classOf[Unit])
    final val FuncEntityGetDistanceToEntity = TypedName(method("func_70032_d"), classOf[Float])
    final val FuncEntityGetDistanceSq_Coord = TypedName(method("func_70092_e"), classOf[Double])
    final val FuncEntityGetDistanceSq_BlockPos = TypedName(method("func_174818_b"), classOf[Double])
    final val FuncEntityGetDistanceSqToCenter = TypedName(method("func_174831_c"), classOf[Double])
    final val FuncEntityGetDistance = TypedName(method("func_70011_f"), classOf[Double])
    final val FuncEntityGetDistanceSqToEntity = TypedName(method("func_70068_e"), classOf[Double])
    final val FuncEntityOnCollideWithPlayer = TypedName(method("func_70100_b_"), classOf[Unit])
    final val FuncEntityApplyEntityCollision = TypedName(method("func_70108_f"), classOf[Unit])
    final val FuncEntityAddVelocity = TypedName(method("func_70024_g"), classOf[Unit])
    final val FuncEntitySetBeenAttacked = TypedName(method("func_70018_K"), classOf[Unit])
    final val FuncEntityAttackEntityFrom = TypedName(method("func_70097_a"), classOf[Boolean])
    final val FuncEntityGetLook = TypedName(method("func_70676_i"), classOf[Vec3d])
    final val FuncEntityGetVectorForRotation = TypedName(method("func_174806_f"), classOf[Vec3d])
    final val FuncEntityGetPositionEyes = TypedName(method("func_174824_e"), classOf[Vec3d])
    final val FuncEntityRayTrace = TypedName(method("func_174822_a"), classOf[RayTraceResult])
    final val FuncEntityCanBeCollidedWith = TypedName(method("func_70067_L"), classOf[Boolean])
    final val FuncEntityCanBePushed = TypedName(method("func_70104_M"), classOf[Boolean])
    final val FuncEntityAddToPlayerScore = TypedName(method("func_70084_c"), classOf[Unit])
    final val FuncEntityIsInRangeToRender3d = TypedName(method("func_145770_h"), classOf[Boolean])
    final val FuncEntityIsInRangeToRenderDist = TypedName(method("func_70112_a"), classOf[Boolean])
    final val FuncEntityWriteToNBTAtomically = TypedName(method("func_184198_c"), classOf[Boolean])
    final val FuncEntityWriteToNBTOptional = TypedName(method("func_70039_c"), classOf[Boolean])
    final val FuncEntityWriteToNBT = TypedName(method("func_70109_d"), classOf[Unit])
    final val FuncEntityReadFromNBT = TypedName(method("func_70020_e"), classOf[Unit])
    final val FuncEntityShouldSetPosAfterLoading = TypedName(method("func_142008_O"), classOf[Boolean])
    final val FuncEntityGetEntityString = TypedName(method("func_70022_Q"), classOf[String])
    final val FuncEntityReadEntityFromNBT = TypedName(method("func_70037_a"), classOf[Unit])
    final val FuncEntityWriteEntityToNBT = TypedName(method("func_70014_b"), classOf[Unit])
    final val FuncEntityOnChunkLoad = TypedName(method("func_110123_P"), classOf[Unit])
    final val FuncEntityNewDoubleNBTList = TypedName(method("func_70087_a"), classOf[NBTTagList])
    final val FuncEntityNewFloatNBTList = TypedName(method("func_70049_a"), classOf[NBTTagList])
    final val FuncEntityDropItem = TypedName(method("func_145779_a"), classOf[EntityItem])
    final val FuncEntityDropItemWithOffset = TypedName(method("func_145778_a"), classOf[EntityItem])
    final val FuncEntityEntityDropItem = TypedName(method("func_70099_a"), classOf[EntityItem])
    final val FuncEntityIsEntityAlive = TypedName(method("func_70089_S"), classOf[Boolean])
    final val FuncEntityIsEntityInsideOpaqueBlock = TypedName(method("func_70094_T"), classOf[Boolean])
    final val FuncEntityProcessInitialInteract = TypedName(method("func_184230_a"), classOf[Boolean])
    final val FuncEntityGetCollisionBox = TypedName(method("func_70114_g"), classOf[AxisAlignedBB])
    final val FuncEntityUpdateRidden = TypedName(method("func_70098_U"), classOf[Unit])
    final val FuncEntityUpdatePassenger = TypedName(method("func_184232_k"), classOf[Unit])
    final val FuncEntityApplyOrientationToEntity = TypedName(method("func_184190_l"), classOf[Unit])
    final val FuncEntityGetYOffset = TypedName(method("func_70033_W"), classOf[Double])
    final val FuncEntityGetMountedYOffset = TypedName(method("func_70042_X"), classOf[Double])
    final val FuncEntityStartRiding = TypedName(method("func_184220_m"), classOf[Boolean])
    final val FuncEntityStartRiding_TwoParam = TypedName(method("func_184205_a"), classOf[Boolean])
    final val FuncEntityCanBeRidden_OneParam = TypedName(method("func_184228_n"), classOf[Boolean])
    final val FuncEntityRemovePassengers = TypedName(method("func_184226_ay"), classOf[Unit])
    final val FuncEntityDismountRidingEntity = TypedName(method("func_184210_p"), classOf[Unit])
    final val FuncEntityAddPassenger = TypedName(method("func_184200_o"), classOf[Unit])
    final val FuncEntityRemovePassenger = TypedName(method("func_184225_p"), classOf[Unit])
    final val FuncEntityCanFitPassenger = TypedName(method("func_184219_q"), classOf[Boolean])
    final val FuncEntitySetPositionAndRotation2 = TypedName(method("func_180426_a"), classOf[Unit])
    final val FuncEntityGetCollisionBorderSize = TypedName(method("func_70111_Y"), classOf[Float])
    final val FuncEntityGetLookVec = TypedName(method("func_70040_Z"), classOf[Vec3d])
    final val FuncEntitySetPortal = TypedName(method("func_181015_d"), classOf[Unit])
    final val FuncEntityGetPortalCooldown = TypedName(method("func_82147_ab"), classOf[Int])
    final val FuncEntitySetVelocity = TypedName(method("func_70016_h"), classOf[Unit])
    final val FuncEntityHandleStatusUpdate = TypedName(method("func_70103_a"), classOf[Unit])
    final val FuncEntityPerformHurtAnimation = TypedName(method("func_70057_ab"), classOf[Unit])
    final val FuncEntityGetHeldEquipment = TypedName(method("func_184214_aD"), classOf[lang.Iterable[ItemStack]])
    final val FuncEntityGetArmorInventoryList = TypedName(method("func_184193_aE"), classOf[lang.Iterable[ItemStack]])
    final val FuncEntityGetEquipmentAndArmor = TypedName(method("func_184209_aF"), classOf[lang.Iterable[ItemStack]])
    final val FuncEntitySetItemStackToSlot = TypedName(method("func_184201_a"), classOf[Unit])
    final val FuncEntityIsBurning = TypedName(method("func_70027_ad"), classOf[Boolean])
    final val FuncEntityIsRiding = TypedName(method("func_184218_aH"), classOf[Boolean])
    final val FuncEntityIsBeingRidden = TypedName(method("func_184207_aI"), classOf[Boolean])
    final val FuncEntityIsSneaking = TypedName(method("func_70093_af"), classOf[Boolean])
    final val FuncEntitySetSneaking = TypedName(method("func_70095_a"), classOf[Unit])
    final val FuncEntityIsSprinting = TypedName(method("func_70051_ag"), classOf[Boolean])
    final val FuncEntitySetSprinting = TypedName(method("func_70031_b"), classOf[Unit])
    final val FuncEntityIsGlowing = TypedName(method("func_184202_aL"), classOf[Boolean])
    final val FuncEntitySetGlowing = TypedName(method("func_184195_f"), classOf[Unit])
    final val FuncEntityIsInvisible = TypedName(method("func_82150_aj"), classOf[Boolean])
    final val FuncEntityIsInvisibleToPlayer = TypedName(method("func_98034_c"), classOf[Boolean])
    final val FuncEntityGetTeam = TypedName(method("func_96124_cp"), classOf[Team])
    final val FuncEntityIsOnSameTeam = TypedName(method("func_184191_r"), classOf[Boolean])
    final val FuncEntityIsOnScoreboardTeam = TypedName(method("func_184194_a"), classOf[Boolean])
    final val FuncEntitySetInvisible = TypedName(method("func_82142_c"), classOf[Unit])
    final val FuncEntityGetFlag = TypedName(method("func_70083_f"), classOf[Boolean])
    final val FuncEntitySetFlag = TypedName(method("func_70052_a"), classOf[Unit])
    final val FuncEntityGetAir = TypedName(method("func_70086_ai"), classOf[Int])
    final val FuncEntitySetAir = TypedName(method("func_70050_g"), classOf[Unit])
    final val FuncEntityOnStruckByLightning = TypedName(method("func_70077_a"), classOf[Unit])
    final val FuncEntityOnKillEntity = TypedName(method("func_70074_a"), classOf[Unit])
    final val FuncEntityPushOutOfBlocks = TypedName(method("func_145771_j"), classOf[Boolean])
    final val FuncEntitySetInWeb = TypedName(method("func_70110_aj"), classOf[Unit])
    final val FuncEntityGetName = TypedName(method("func_70005_c_"), classOf[String])
    final val FuncEntityGetParts = TypedName(method("func_70021_al"), classOf[Array[Entity]])
    final val FuncEntityIsEntityEqual = TypedName(method("func_70028_i"), classOf[Boolean])
    final val FuncEntityGetRotationYawHead = TypedName(method("func_70079_am"), classOf[Float])
    final val FuncEntitySetRotationYawHead = TypedName(method("func_70034_d"), classOf[Unit])
    final val FuncEntitySetRenderYawOffset = TypedName(method("func_181013_g"), classOf[Unit])
    final val FuncEntityCanAttackWithItem = TypedName(method("func_70075_an"), classOf[Boolean])
    final val FuncEntityHitByEntity = TypedName(method("func_85031_j"), classOf[Boolean])
    final val FuncEntityToString = TypedName("toString", classOf[String])
    final val FuncEntityIsEntityInvulnerable = TypedName(method("func_180431_b"), classOf[Boolean])
    final val FuncEntitySetEntityInvulnerable = TypedName(method("func_184224_h"), classOf[Unit])
    final val FuncEntityCopyLocationAndAnglesFrom = TypedName(method("func_82149_j"), classOf[Unit])
    final val FuncEntityCopyDataFromOld = TypedName(method("func_180432_n"), classOf[Unit])
    final val FuncEntityChangeDimension = TypedName(method("func_184204_a"), classOf[Entity])
    final val FuncEntityIsNonBoss = TypedName(method("func_184222_aU"), classOf[Boolean])
    final val FuncEntityGetExplosionResistance = TypedName(method("func_180428_a"), classOf[Float])
    final val FuncEntityVerifyExplosion = TypedName(method("func_174816_a"), classOf[Boolean])
    final val FuncEntityGetMaxFallHeight = TypedName(method("func_82143_as"), classOf[Int])
    final val FuncEntityGetLastPortalVec = TypedName(method("func_181014_aG"), classOf[Vec3d])
    final val FuncEntityGetTeleportDirection = TypedName(method("func_181012_aH"), classOf[EnumFacing])
    final val FuncEntityDoesEntityNotTriggerPressurePlate = TypedName(method("func_145773_az"), classOf[Boolean])
    final val FuncEntityAddEntityCrashInfo = TypedName(method("func_85029_a"), classOf[Unit])
    final val FuncEntitySetUniqueId = TypedName(method("func_184221_a"), classOf[Unit])
    final val FuncEntityCanRenderOnFire = TypedName(method("func_90999_ad"), classOf[Boolean])
    final val FuncEntityGetUniqueID = TypedName(method("func_110124_au"), classOf[UUID])
    final val FuncEntityIsPushedByWater = TypedName(method("func_96092_aw"), classOf[Boolean])
    final val FuncEntityGetDisplayName = TypedName(method("func_145748_c_"), classOf[ITextComponent])
    final val FuncEntitySetCustomNameTag = TypedName(method("func_96094_a"), classOf[Unit])
    final val FuncEntityGetCustomNameTag = TypedName(method("func_95999_t"), classOf[String])
    final val FuncEntityHasCustomName = TypedName(method("func_145818_k_"), classOf[Boolean])
    final val FuncEntitySetAlwaysRenderNameTag = TypedName(method("func_174805_g"), classOf[Unit])
    final val FuncEntityGetAlwaysRenderNameTag = TypedName(method("func_174833_aM"), classOf[Boolean])
    final val FuncEntitySetPositionAndUpdate = TypedName(method("func_70634_a"), classOf[Unit])
    final val FuncEntityNotifyDataManagerChange = TypedName(method("func_184206_a"), classOf[Unit])
    final val FuncEntityGetAlwaysRenderNameTagForRender = TypedName(method("func_94059_bO"), classOf[Boolean])
    final val FuncEntityGetHorizontalFacing = TypedName(method("func_174811_aO"), classOf[EnumFacing])
    final val FuncEntityGetAdjustedHorizontalFacing = TypedName(method("func_184172_bi"), classOf[EnumFacing])
    final val FuncEntityGetHoverEvent = TypedName(method("func_174823_aP"), classOf[HoverEvent])
    final val FuncEntityIsSpectatedByPlayer = TypedName(method("func_174827_a"), classOf[Boolean])
    final val FuncEntityGetEntityBoundingBox = TypedName(method("func_174813_aQ"), classOf[AxisAlignedBB])
    final val FuncEntityGetRenderBoundingBox = TypedName(method("func_184177_bl"), classOf[AxisAlignedBB])
    final val FuncEntitySetEntityBoundingBox = TypedName(method("func_174826_a"), classOf[Unit])
    final val FuncEntityGetEyeHeight = TypedName(method("func_70047_e"), classOf[Float])
    final val FuncEntityIsOutsideBorder = TypedName(method("func_174832_aS"), classOf[Boolean])
    final val FuncEntitySetOutsideBorder = TypedName(method("func_174821_h"), classOf[Unit])
    final val FuncEntityReplaceItemInInventory = TypedName(method("func_174820_d"), classOf[Boolean])
    final val FuncEntityAddChatMessage = TypedName(method("func_145747_a"), classOf[Unit])
    final val FuncEntityCanCommandSenderUseCommand = TypedName(method("func_70003_b"), classOf[Boolean])
    final val FuncEntityGetPosition = TypedName(method("func_180425_c"), classOf[BlockPos])
    final val FuncEntityGetPositionVector = TypedName(method("func_174791_d"), classOf[Vec3d])
    final val FuncEntityGetEntityWorld = TypedName(method("func_130014_f_"), classOf[World])
    final val FuncEntityGetCommandSenderEntity = TypedName(method("func_174793_f"), classOf[Entity])
    final val FuncEntitySendCommandFeedback = TypedName(method("func_174792_t_"), classOf[Boolean])
    final val FuncEntitySetCommandStat = TypedName(method("func_174794_a"), classOf[Unit])
    final val FuncEntityGetServer = TypedName(method("func_184102_h"), classOf[MinecraftServer])
    final val FuncEntityGetCommandStats = TypedName(method("func_174807_aT"), classOf[CommandResultStats])
    final val FuncEntitySetCommandStats = TypedName(method("func_174817_o"), classOf[Unit])
    final val FuncEntityApplyPlayerInteraction = TypedName(method("func_184199_a"), classOf[EnumActionResult])
    final val FuncEntityIsImmuneToExplosions = TypedName(method("func_180427_aV"), classOf[Boolean])
    final val FuncEntityApplyEnchantments = TypedName(method("func_174815_a"), classOf[Unit])
    final val FuncEntitySetBossVisibleTo = TypedName(method("func_184178_b"), classOf[Unit])
    final val FuncEntitySetBossNonVisibleTo = TypedName(method("func_184203_c"), classOf[Unit])
    final val FuncEntityGetRotatedYaw = TypedName(method("func_184229_a"), classOf[Float])
    final val FuncEntityGetMirroredYaw = TypedName(method("func_184217_a"), classOf[Float])
    final val FuncEntityFunc_184213_bq = TypedName("func_184213_bq", classOf[Boolean])
    final val FuncEntitySetPositionNonDirty = TypedName(method("func_184189_br"), classOf[Boolean])
    final val FuncEntityGetControllingPassenger = TypedName(method("func_184179_bs"), classOf[Entity])
    final val FuncEntityGetPassengers = TypedName(method("func_184188_bt"), classOf[util.List[Entity]])
    final val FuncEntityIsPassenger = TypedName(method("func_184196_w"), classOf[Boolean])
    final val FuncEntityGetRecursivePassengers = TypedName(method("func_184182_bu"), classOf[util.Collection[Entity]])
    final val FuncEntityGetRecursivePassengersByType = TypedName(method("func_184180_b"), classOf[util.Collection[_ <: Entity]])
    final val FuncEntityGetLowestRidingEntity = TypedName(method("func_184208_bv"), classOf[Entity])
    final val FuncEntityIsRidingSameEntity = TypedName(method("func_184223_x"), classOf[Boolean])
    final val FuncEntityIsRidingOrBeingRiddenBy = TypedName(method("func_184215_y"), classOf[Boolean])
    final val FuncEntityCanPassengerSteer = TypedName(method("func_184186_bw"), classOf[Boolean])
    final val FuncEntityGetRidingEntity = TypedName(method("func_184187_bx"), classOf[Entity])
    final val FuncEntityGetPushReaction = TypedName(method("func_184192_z"), classOf[EnumPushReaction])
    final val FuncEntityGetSoundCategory = TypedName(method("func_184176_by"), classOf[SoundCategory])
}
