package com.seremis.geninfusion.api.lib

import java.util
import java.util.{Random, UUID}

import com.seremis.geninfusion.api.util.TypedName
import com.seremis.geninfusion.util.MCPNames._
import net.minecraft.command.CommandResultStats
import net.minecraft.entity.Entity
import net.minecraft.item.ItemStack
import net.minecraft.network.datasync.{DataParameter, EntityDataManager}
import net.minecraft.util.EnumFacing
import net.minecraft.util.math.{AxisAlignedBB, BlockPos, Vec3d}
import net.minecraft.world.World
import org.apache.logging.log4j.Logger

object VariableLib {
    final val VarEntityLOGGER = TypedName(field("field_184243_a"), classOf[Logger])
    final val VarEntityZERO_AABB = TypedName(field("field_174836_a"), classOf[AxisAlignedBB])
    final val VarEntityRenderDistanceWeight = TypedName(field("field_70155_l"), classOf[Double])
    final val VarEntityNextEntityID = TypedName(field("field_70152_a"), classOf[Int])
    final val VarEntityEntityId = TypedName(field("field_145783_c"), classOf[Int])
    final val VarEntityPreventEntitySpawning = TypedName(field("field_70156_m"), classOf[Boolean])
    final val VarEntityRiddenByEntities = TypedName(field("field_184244_h"), classOf[util.List[Entity]])
    final val VarEntityRideCooldown = TypedName(field("field_184245_j"), classOf[Int])
    final val VarEntityRidingEntity = TypedName(field("field_184239_as"), classOf[Entity])
    final val VarEntityForceSpawn = TypedName(field("field_98038_p"), classOf[Boolean])
    final val VarEntityWorldObj = TypedName(field("field_70170_p"), classOf[World])
    final val VarEntityPrevPosX = TypedName(field("field_70169_q"), classOf[Double])
    final val VarEntityPrevPosY = TypedName(field("field_70167_r"), classOf[Double])
    final val VarEntityPrevPosZ = TypedName(field("field_70166_s"), classOf[Double])
    final val VarEntityPosX = TypedName(field("field_70165_t"), classOf[Double])
    final val VarEntityPosY = TypedName(field("field_70163_u"), classOf[Double])
    final val VarEntityPosZ = TypedName(field("field_70161_v"), classOf[Double])
    final val VarEntityMotionX = TypedName(field("field_70159_w"), classOf[Double])
    final val VarEntityMotionY = TypedName(field("field_70181_x"), classOf[Double])
    final val VarEntityMotionZ = TypedName(field("field_70179_y"), classOf[Double])
    final val VarEntityRotationYaw = TypedName(field("field_70177_z"), classOf[Float])
    final val VarEntityRotationPitch = TypedName(field("field_70125_A"), classOf[Float])
    final val VarEntityPrevRotationYaw = TypedName(field("field_70126_B"), classOf[Float])
    final val VarEntityPrevRotationPitch = TypedName(field("field_70127_C"), classOf[Float])
    final val VarEntityBoundingBox = TypedName(field("field_70121_D"), classOf[AxisAlignedBB])
    final val VarEntityOnGround = TypedName(field("field_70122_E"), classOf[Boolean])
    final val VarEntityIsCollidedHorizontally = TypedName(field("field_70123_F"), classOf[Boolean])
    final val VarEntityIsCollidedVertically = TypedName(field("field_70124_G"), classOf[Boolean])
    final val VarEntityIsCollided = TypedName(field("field_70132_H"), classOf[Boolean])
    final val VarEntityVelocityChanged = TypedName(field("field_70133_I"), classOf[Boolean])
    final val VarEntityIsInWeb = TypedName(field("field_70134_J"), classOf[Boolean])
    final val VarEntityIsOutsideBorder = TypedName(field("field_174835_g"), classOf[Boolean])
    final val VarEntityIsDead = TypedName(field("field_70128_L"), classOf[Boolean])
    final val VarEntityWidth = TypedName(field("field_70130_N"), classOf[Float])
    final val VarEntityHeight = TypedName(field("field_70131_O"), classOf[Float])
    final val VarEntityPrevDistanceWalkedModified = TypedName(field("field_70141_P"), classOf[Float])
    final val VarEntityDistanceWalkedModified = TypedName(field("field_70140_Q"), classOf[Float])
    final val VarEntityDistanceWalkedOnStepModified = TypedName(field("field_82151_R"), classOf[Float])
    final val VarEntityFallDistance = TypedName(field("field_70143_R"), classOf[Float])
    final val VarEntityNextStepDistance = TypedName(field("field_70150_b"), classOf[Int])
    final val VarEntityLastTickPosX = TypedName(field("field_70142_S"), classOf[Double])
    final val VarEntityLastTickPosY = TypedName(field("field_70137_T"), classOf[Double])
    final val VarEntityLastTickPosZ = TypedName(field("field_70136_U"), classOf[Double])
    final val VarEntityStepHeight = TypedName(field("field_70138_W"), classOf[Float])
    final val VarEntityNoClip = TypedName(field("field_70145_X"), classOf[Boolean])
    final val VarEntityEntityCollisionReduction = TypedName(field("field_70144_Y"), classOf[Float])
    final val VarEntityRand = TypedName(field("field_70146_Z"), classOf[Random])
    final val VarEntityTicksExisted = TypedName(field("field_70173_aa"), classOf[Int])
    final val VarEntityFireResistance = TypedName(field("field_70174_ab"), classOf[Int])
    final val VarEntityFire = TypedName(field("field_70151_c"), classOf[Int])
    final val VarEntityInWater = TypedName(field("field_70171_ac"), classOf[Boolean])
    final val VarEntityHurtResistantTime = TypedName(field("field_70172_ad"), classOf[Int])
    final val VarEntityFirstUpdate = TypedName(field("field_70148_d"), classOf[Boolean])
    final val VarEntityIsImmuneToFire = TypedName(field("field_70178_ae"), classOf[Boolean])
    final val VarEntityDataManager = TypedName(field("field_70180_af"), classOf[EntityDataManager])
    final val VarEntityFLAGS = TypedName(field("field_184240_ax"), classOf[DataParameter[Byte]])
    final val VarEntityAIR = TypedName(field("field_184241_ay"), classOf[DataParameter[Integer]])
    final val VarEntityCUSTOM_NAME = TypedName(field("field_184242_az"), classOf[DataParameter[String]])
    final val VarEntityCUSTOM_NAME_VISIBLE = TypedName(field("field_184233_aA"), classOf[DataParameter[Boolean]])
    final val VarEntitySILENT = TypedName(field("field_184234_aB"), classOf[DataParameter[Boolean]])
    final val VarEntityAddedToChunk = TypedName(field("field_70175_ag"), classOf[Boolean])
    final val VarEntityChunkCoordX = TypedName(field("field_70176_ah"), classOf[Int])
    final val VarEntityChunkCoordY = TypedName(field("field_70162_ai"), classOf[Int])
    final val VarEntityChunkCoordZ = TypedName(field("field_70164_aj"), classOf[Int])
    final val VarEntityServerPosX = TypedName(field("field_70118_ct"), classOf[Long])
    final val VarEntityServerPosY = TypedName(field("field_70117_cu"), classOf[Long])
    final val VarEntityServerPosZ = TypedName(field("field_70116_cv"), classOf[Long])
    final val VarEntityIgnoreFrustumCheck = TypedName(field("field_70158_ak"), classOf[Boolean])
    final val VarEntityIsAirBorne = TypedName(field("field_70160_al"), classOf[Boolean])
    final val VarEntityTimeUntilPortal = TypedName(field("field_71088_bW"), classOf[Int])
    final val VarEntityInPortal = TypedName(field("field_71087_bX"), classOf[Boolean])
    final val VarEntityPortalCounter = TypedName(field("field_82153_h"), classOf[Int])
    final val VarEntityDimension = TypedName(field("field_71093_bK"), classOf[Int])
    final val VarEntityLastPortalPos = TypedName(field("field_181016_an"), classOf[BlockPos])
    final val VarEntityLastPortalVec = TypedName(field("field_181017_ao"), classOf[Vec3d])
    final val VarEntityTeleportDirection = TypedName(field("field_181018_ap"), classOf[EnumFacing])
    final val VarEntityInvulnerable = TypedName(field("field_83001_bt"), classOf[Boolean])
    final val VarEntityEntityUniqueID = TypedName(field("field_96093_i"), classOf[UUID])
    final val VarEntityCmdResultStats = TypedName(field("field_174837_as"), classOf[CommandResultStats])
    final val VarEntityEmptyItemStackList = TypedName(field("field_184235_aE"), classOf[util.List[ItemStack]])
    final val VarEntityGlowing = TypedName(field("field_184238_ar"), classOf[Boolean])
    final val VarEntityTags = TypedName(field("field_184236_aF"), classOf[util.Set[String]])
    final val VarEntityIsPositionDirty = TypedName(field("field_184237_aG"), classOf[Boolean])
}
