package com.seremis.geninfusion.api.lib

import java.util
import java.util.{Random, UUID}

import com.seremis.geninfusion.api.util.TypedName
import com.seremis.geninfusion.util.MCPNames._
import net.minecraft.command.CommandResultStats
import net.minecraft.entity.ai._
import net.minecraft.entity.ai.attributes.{AbstractAttributeMap, AttributeModifier}
import net.minecraft.entity.player.EntityPlayer
import net.minecraft.entity.{Entity, EntityBodyHelper, EntityLivingBase}
import net.minecraft.item.ItemStack
import net.minecraft.nbt.NBTTagCompound
import net.minecraft.network.datasync.{DataParameter, EntityDataManager}
import net.minecraft.pathfinding.{PathNavigate, PathNodeType}
import net.minecraft.potion.{Potion, PotionEffect}
import net.minecraft.util.math.{AxisAlignedBB, BlockPos, Vec3d}
import net.minecraft.util.{CombatTracker, EnumFacing, EnumHand, ResourceLocation}
import net.minecraft.world.World
import org.apache.logging.log4j.Logger

object VariableLib {
    final val VarEntityAIR = TypedName(field("field_184241_ay"), classOf[DataParameter[Integer]])
    final val VarEntityAddedToChunk = TypedName(field("field_70175_ag"), classOf[Boolean])
    final val VarEntityBoundingBox = TypedName(field("field_70121_D"), classOf[AxisAlignedBB])
    final val VarEntityCUSTOM_NAME = TypedName(field("field_184242_az"), classOf[DataParameter[String]])
    final val VarEntityCUSTOM_NAME_VISIBLE = TypedName(field("field_184233_aA"), classOf[DataParameter[Boolean]])
    final val VarEntityChunkCoordX = TypedName(field("field_70176_ah"), classOf[Int])
    final val VarEntityChunkCoordY = TypedName(field("field_70162_ai"), classOf[Int])
    final val VarEntityChunkCoordZ = TypedName(field("field_70164_aj"), classOf[Int])
    final val VarEntityCmdResultStats = TypedName(field("field_174837_as"), classOf[CommandResultStats])
    final val VarEntityDataManager = TypedName(field("field_70180_af"), classOf[EntityDataManager])
    final val VarEntityDimension = TypedName(field("field_71093_bK"), classOf[Int])
    final val VarEntityDistanceWalkedModified = TypedName(field("field_70140_Q"), classOf[Float])
    final val VarEntityDistanceWalkedOnStepModified = TypedName(field("field_82151_R"), classOf[Float])
    final val VarEntityEmptyItemStackList = TypedName(field("field_184235_aE"), classOf[util.List[ItemStack]])
    final val VarEntityEntityCollisionReduction = TypedName(field("field_70144_Y"), classOf[Float])
    final val VarEntityEntityId = TypedName(field("field_145783_c"), classOf[Int])
    final val VarEntityEntityUniqueID = TypedName(field("field_96093_i"), classOf[UUID])
    final val VarEntityFLAGS = TypedName(field("field_184240_ax"), classOf[DataParameter[Byte]])
    final val VarEntityFallDistance = TypedName(field("field_70143_R"), classOf[Float])
    final val VarEntityFire = TypedName(field("field_70151_c"), classOf[Int])
    final val VarEntityFireResistance = TypedName(field("field_70174_ab"), classOf[Int])
    final val VarEntityFirstUpdate = TypedName(field("field_70148_d"), classOf[Boolean])
    final val VarEntityForceSpawn = TypedName(field("field_98038_p"), classOf[Boolean])
    final val VarEntityGlowing = TypedName(field("field_184238_ar"), classOf[Boolean])
    final val VarEntityHeight = TypedName(field("field_70131_O"), classOf[Float])
    final val VarEntityHurtResistantTime = TypedName(field("field_70172_ad"), classOf[Int])
    final val VarEntityIgnoreFrustumCheck = TypedName(field("field_70158_ak"), classOf[Boolean])
    final val VarEntityInPortal = TypedName(field("field_71087_bX"), classOf[Boolean])
    final val VarEntityInWater = TypedName(field("field_70171_ac"), classOf[Boolean])
    final val VarEntityInvulnerable = TypedName(field("field_83001_bt"), classOf[Boolean])
    final val VarEntityIsAirBorne = TypedName(field("field_70160_al"), classOf[Boolean])
    final val VarEntityIsCollided = TypedName(field("field_70132_H"), classOf[Boolean])
    final val VarEntityIsCollidedHorizontally = TypedName(field("field_70123_F"), classOf[Boolean])
    final val VarEntityIsCollidedVertically = TypedName(field("field_70124_G"), classOf[Boolean])
    final val VarEntityIsDead = TypedName(field("field_70128_L"), classOf[Boolean])
    final val VarEntityIsImmuneToFire = TypedName(field("field_70178_ae"), classOf[Boolean])
    final val VarEntityIsInWeb = TypedName(field("field_70134_J"), classOf[Boolean])
    final val VarEntityIsOutsideBorder = TypedName(field("field_174835_g"), classOf[Boolean])
    final val VarEntityIsPositionDirty = TypedName(field("field_184237_aG"), classOf[Boolean])
    final val VarEntityLOGGER = TypedName(field("field_184243_a"), classOf[Logger])
    final val VarEntityLastPortalPos = TypedName(field("field_181016_an"), classOf[BlockPos])
    final val VarEntityLastPortalVec = TypedName(field("field_181017_ao"), classOf[Vec3d])
    final val VarEntityLastTickPosX = TypedName(field("field_70142_S"), classOf[Double])
    final val VarEntityLastTickPosY = TypedName(field("field_70137_T"), classOf[Double])
    final val VarEntityLastTickPosZ = TypedName(field("field_70136_U"), classOf[Double])
    final val VarEntityMotionX = TypedName(field("field_70159_w"), classOf[Double])
    final val VarEntityMotionY = TypedName(field("field_70181_x"), classOf[Double])
    final val VarEntityMotionZ = TypedName(field("field_70179_y"), classOf[Double])
    final val VarEntityNextEntityID = TypedName(field("field_70152_a"), classOf[Int])
    final val VarEntityNextStepDistance = TypedName(field("field_70150_b"), classOf[Int])
    final val VarEntityNoClip = TypedName(field("field_70145_X"), classOf[Boolean])
    final val VarEntityOnGround = TypedName(field("field_70122_E"), classOf[Boolean])
    final val VarEntityPortalCounter = TypedName(field("field_82153_h"), classOf[Int])
    final val VarEntityPosX = TypedName(field("field_70165_t"), classOf[Double])
    final val VarEntityPosY = TypedName(field("field_70163_u"), classOf[Double])
    final val VarEntityPosZ = TypedName(field("field_70161_v"), classOf[Double])
    final val VarEntityPrevDistanceWalkedModified = TypedName(field("field_70141_P"), classOf[Float])
    final val VarEntityPrevPosX = TypedName(field("field_70169_q"), classOf[Double])
    final val VarEntityPrevPosY = TypedName(field("field_70167_r"), classOf[Double])
    final val VarEntityPrevPosZ = TypedName(field("field_70166_s"), classOf[Double])
    final val VarEntityPrevRotationPitch = TypedName(field("field_70127_C"), classOf[Float])
    final val VarEntityPrevRotationYaw = TypedName(field("field_70126_B"), classOf[Float])
    final val VarEntityPreventEntitySpawning = TypedName(field("field_70156_m"), classOf[Boolean])
    final val VarEntityRand = TypedName(field("field_70146_Z"), classOf[Random])
    final val VarEntityRenderDistanceWeight = TypedName(field("field_70155_l"), classOf[Double])
    final val VarEntityRiddenByEntities = TypedName(field("field_184244_h"), classOf[util.List[Entity]])
    final val VarEntityRideCooldown = TypedName(field("field_184245_j"), classOf[Int])
    final val VarEntityRidingEntity = TypedName(field("field_184239_as"), classOf[Entity])
    final val VarEntityRotationPitch = TypedName(field("field_70125_A"), classOf[Float])
    final val VarEntityRotationYaw = TypedName(field("field_70177_z"), classOf[Float])
    final val VarEntitySILENT = TypedName(field("field_184234_aB"), classOf[DataParameter[Boolean]])
    final val VarEntityServerPosX = TypedName(field("field_70118_ct"), classOf[Long])
    final val VarEntityServerPosY = TypedName(field("field_70117_cu"), classOf[Long])
    final val VarEntityServerPosZ = TypedName(field("field_70116_cv"), classOf[Long])
    final val VarEntityStepHeight = TypedName(field("field_70138_W"), classOf[Float])
    final val VarEntityTags = TypedName(field("field_184236_aF"), classOf[util.Set[String]])
    final val VarEntityTeleportDirection = TypedName(field("field_181018_ap"), classOf[EnumFacing])
    final val VarEntityTicksExisted = TypedName(field("field_70173_aa"), classOf[Int])
    final val VarEntityTimeUntilPortal = TypedName(field("field_71088_bW"), classOf[Int])
    final val VarEntityVelocityChanged = TypedName(field("field_70133_I"), classOf[Boolean])
    final val VarEntityWidth = TypedName(field("field_70130_N"), classOf[Float])
    final val VarEntityWorldObj = TypedName(field("field_70170_p"), classOf[World])
    final val VarEntityZERO_AABB = TypedName(field("field_174836_a"), classOf[AxisAlignedBB])
    final val VarEntityLivingAI_FLAGS = TypedName(field("field_184654_a"), classOf[DataParameter[Byte]])
    final val VarEntityLivingAttackTarget = TypedName(field("field_70696_bz"), classOf[EntityLivingBase])
    final val VarEntityLivingBodyHelper = TypedName(field("field_70762_j"), classOf[EntityBodyHelper])
    final val VarEntityLivingCanPickUpLoot = TypedName(field("field_82172_bs"), classOf[Boolean])
    final val VarEntityLivingDeathLootTable = TypedName(field("field_184659_bA"), classOf[ResourceLocation])
    final val VarEntityLivingDeathLootTableSeed = TypedName(field("field_184653_bB"), classOf[Long])
    final val VarEntityLivingExperienceValue = TypedName(field("field_70728_aV"), classOf[Int])
    final val VarEntityLivingInventoryArmor = TypedName(field("field_184657_bw"), classOf[Array[ItemStack]])
    final val VarEntityLivingInventoryArmorDropChances = TypedName(field("field_184655_bs"), classOf[Array[Float]])
    final val VarEntityLivingInventoryHands = TypedName(field("field_184656_bv"), classOf[Array[ItemStack]])
    final val VarEntityLivingInventoryHandsDropChances = TypedName(field("field_82174_bp"), classOf[Array[Float]])
    final val VarEntityLivingIsLeashed = TypedName(field("field_110169_bv"), classOf[Boolean])
    final val VarEntityLivingJumpHelper = TypedName(field("field_70767_i"), classOf[EntityJumpHelper])
    final val VarEntityLivingLeashNBTTag = TypedName(field("field_110170_bx"), classOf[NBTTagCompound])
    final val VarEntityLivingLeashedToEntity = TypedName(field("field_110168_bw"), classOf[Entity])
    final val VarEntityLivingLivingSoundTime = TypedName(field("field_70757_a"), classOf[Int])
    final val VarEntityLivingLookHelper = TypedName(field("field_70749_g"), classOf[EntityLookHelper])
    final val VarEntityLivingMapPathPriority = TypedName(field("field_184658_bz"), classOf[Map[PathNodeType, Float]])
    final val VarEntityLivingMoveHelper = TypedName(field("field_70765_h"), classOf[EntityMoveHelper])
    final val VarEntityLivingNavigator = TypedName(field("field_70699_by"), classOf[PathNavigate])
    final val VarEntityLivingPersistenceRequired = TypedName(field("field_82179_bU"), classOf[Boolean])
    final val VarEntityLivingSenses = TypedName(field("field_70723_bA"), classOf[EntitySenses])
    final val VarEntityLivingTargetTasks = TypedName(field("field_70715_bh"), classOf[EntityAITasks])
    final val VarEntityLivingTasks = TypedName(field("field_70714_bg"), classOf[EntityAITasks])
    final val VarEntityLivingBaseARROW_COUNT_IN_ENTITY = TypedName(field("field_184635_h"), classOf[DataParameter[Integer]])
    final val VarEntityLivingBaseAbsorptionAmount = TypedName(field("field_110151_bq"), classOf[Float])
    final val VarEntityLivingBaseActiveItemStack = TypedName(field("field_184627_bm"), classOf[ItemStack])
    final val VarEntityLivingBaseActiveItemStackUseCount = TypedName(field("field_184628_bn"), classOf[Int])
    final val VarEntityLivingBaseActivePotionsMap = TypedName(field("field_70713_bf"), classOf[Map[Potion, PotionEffect]])
    final val VarEntityLivingBaseArmorArray = TypedName(field("field_184631_bt"), classOf[Array[ItemStack]])
    final val VarEntityLivingBaseArrowHitTimer = TypedName(field("field_70720_be"), classOf[Int])
    final val VarEntityLivingBaseAttackedAtYaw = TypedName(field("field_70739_aP"), classOf[Float])
    final val VarEntityLivingBaseAttackingPlayer = TypedName(field("field_70717_bb"), classOf[EntityPlayer])
    final val VarEntityLivingBaseAttributeMap = TypedName(field("field_110155_d"), classOf[AbstractAttributeMap])
    final val VarEntityLivingBaseCameraPitch = TypedName(field("field_70726_aT"), classOf[Float])
    final val VarEntityLivingBaseDead = TypedName(field("field_70729_aU"), classOf[Boolean])
    final val VarEntityLivingBaseDeathTime = TypedName(field("field_70725_aQ"), classOf[Int])
    final val VarEntityLivingBaseEntityAge = TypedName(field("field_70708_bq"), classOf[Int])
    final val VarEntityLivingBaseEntityLivingToAttack = TypedName(field("field_70755_b"), classOf[EntityLivingBase])
    final val VarEntityLivingBaseHAND_STATES = TypedName(field("field_184621_as"), classOf[DataParameter[Byte]])
    final val VarEntityLivingBaseHEALTH = TypedName(field("field_184632_c"), classOf[DataParameter[Float]])
    final val VarEntityLivingBaseHIDE_PARTICLES = TypedName(field("field_184634_g"), classOf[DataParameter[Boolean]])
    final val VarEntityLivingBaseHandInventory = TypedName(field("field_184630_bs"), classOf[Array[ItemStack]])
    final val VarEntityLivingBaseHurtTime = TypedName(field("field_70737_aN"), classOf[Int])
    final val VarEntityLivingBaseInterpTargetX = TypedName(field("field_184623_bh"), classOf[Double])
    final val VarEntityLivingBaseInterpTargetY = TypedName(field("field_184624_bi"), classOf[Double])
    final val VarEntityLivingBaseInterpTargetYaw = TypedName(field("field_184626_bk"), classOf[Double])
    final val VarEntityLivingBaseInterpTargetZ = TypedName(field("field_184625_bj"), classOf[Double])
    final val VarEntityLivingBaseIsJumping = TypedName(field("field_70703_bu"), classOf[Boolean])
    final val VarEntityLivingBaseIsSwingInProgress = TypedName(field("field_82175_bq"), classOf[Boolean])
    final val VarEntityLivingBaseJumpMovementFactor = TypedName(field("field_70747_aH"), classOf[Float])
    final val VarEntityLivingBaseJumpTicks = TypedName(field("field_70773_bE"), classOf[Int])
    final val VarEntityLivingBaseLandMovementFactor = TypedName(field("field_70746_aG"), classOf[Float])
    final val VarEntityLivingBaseLastAttacker = TypedName(field("field_110150_bn"), classOf[EntityLivingBase])
    final val VarEntityLivingBaseLastAttackerTime = TypedName(field("field_142016_bo"), classOf[Int])
    final val VarEntityLivingBaseLastDamage = TypedName(field("field_110153_bc"), classOf[Float])
    final val VarEntityLivingBaseLimbSwing = TypedName(field("field_184619_aG"), classOf[Float])
    final val VarEntityLivingBaseLimbSwingAmount = TypedName(field("field_70721_aZ"), classOf[Float])
    final val VarEntityLivingBaseMaxHurtResistantTime = TypedName(field("field_70771_an"), classOf[Int])
    final val VarEntityLivingBaseMaxHurtTime = TypedName(field("field_70738_aO"), classOf[Int])
    final val VarEntityLivingBaseMoveForward = TypedName(field("field_70701_bs"), classOf[Float])
    final val VarEntityLivingBaseMoveStrafing = TypedName(field("field_70702_br"), classOf[Float])
    final val VarEntityLivingBaseMovedDistance = TypedName(field("field_70764_aw"), classOf[Float])
    final val VarEntityLivingBaseNewPosRotationIncrements = TypedName(field("field_70716_bi"), classOf[Int])
    final val VarEntityLivingBaseNewPosX = TypedName(field("field_70709_bj"), classOf[Double])
    final val VarEntityLivingBaseOnGroundSpeedFactor = TypedName(field("field_110154_aX"), classOf[Float])
    final val VarEntityLivingBasePOTION_EFFECTS = TypedName(field("field_184633_f"), classOf[DataParameter[Integer]])
    final val VarEntityLivingBasePotionsNeedUpdate = TypedName(field("field_70752_e"), classOf[Boolean])
    final val VarEntityLivingBasePrevBlockpos = TypedName(field("field_184620_bC"), classOf[BlockPos])
    final val VarEntityLivingBasePrevCameraPitch = TypedName(field("field_70727_aS"), classOf[Float])
    final val VarEntityLivingBasePrevLimbSwingAmount = TypedName(field("field_184618_aE"), classOf[Float])
    final val VarEntityLivingBasePrevMovedDistance = TypedName(field("field_70763_ax"), classOf[Float])
    final val VarEntityLivingBasePrevOnGroundSpeedFactor = TypedName(field("field_70768_au"), classOf[Float])
    final val VarEntityLivingBasePrevRenderYawOffset = TypedName(field("field_70760_ar"), classOf[Float])
    final val VarEntityLivingBasePrevRotationYawHead = TypedName(field("field_70758_at"), classOf[Float])
    final val VarEntityLivingBasePrevSwingProgress = TypedName(field("field_70732_aI"), classOf[Float])
    final val VarEntityLivingBaseRandomUnused1 = TypedName(field("field_70770_ap"), classOf[Float])
    final val VarEntityLivingBaseRandomUnused2 = TypedName(field("field_70769_ao"), classOf[Float])
    final val VarEntityLivingBaseRandomYawVelocity = TypedName(field("field_70704_bt"), classOf[Float])
    final val VarEntityLivingBaseRecentlyHit = TypedName(field("field_70718_bc"), classOf[Int])
    final val VarEntityLivingBaseRenderYawOffset = TypedName(field("field_70761_aq"), classOf[Float])
    final val VarEntityLivingBaseRevengeTimer = TypedName(field("field_70756_c"), classOf[Int])
    final val VarEntityLivingBaseRotationYawHead = TypedName(field("field_70759_as"), classOf[Float])
    final val VarEntityLivingBaseScoreValue = TypedName(field("field_70744_aE"), classOf[Int])
    final val VarEntityLivingBaseSprintingSpeedBoostModifier = TypedName(field("field_110157_c"), classOf[AttributeModifier])
    final val VarEntityLivingBaseSprintingSpeedBoostModifierUUID = TypedName(field("field_110156_b"), classOf[UUID])
    final val VarEntityLivingBaseSwingProgress = TypedName(field("field_70733_aJ"), classOf[Float])
    final val VarEntityLivingBaseSwingProgressInt = TypedName(field("field_110158_av"), classOf[Int])
    final val VarEntityLivingBaseSwingingHand = TypedName(field("field_184622_au"), classOf[EnumHand])
    final val VarEntityLivingBaseTicksElytraFlying = TypedName(field("field_184629_bo"), classOf[Int])
    final val VarEntityLivingBaseTicksSinceLastSwing = TypedName(field("field_184617_aD"), classOf[Int])
    final val VarEntityLivingBaseUnused180 = TypedName(field("field_70741_aB"), classOf[Float])
    final val VarEntityLivingBase_combatTracker = TypedName(field("field_94063_bt"), classOf[CombatTracker])
}
