package com.seremis.geninfusion.soulentity

import java.util.{Random, UUID}
import java.{lang, util}

import com.seremis.geninfusion.api.GIApiInterface
import com.seremis.geninfusion.api.genetics.ISoul
import com.seremis.geninfusion.api.lib.FunctionLib
import com.seremis.geninfusion.api.lib.FunctionLib._
import com.seremis.geninfusion.api.soulentity.ISoulEntity
import com.seremis.geninfusion.api.util.TypedName
import com.seremis.geninfusion.soulentity.logic.{FieldLogic, MethodLogic}
import com.seremis.geninfusion.util.UtilNBT
import io.netty.buffer.ByteBuf
import net.minecraft.block.Block
import net.minecraft.block.material.{EnumPushReaction, Material}
import net.minecraft.block.state.IBlockState
import net.minecraft.command.CommandResultStats
import net.minecraft.command.CommandResultStats.Type
import net.minecraft.crash.CrashReportCategory
import net.minecraft.entity._
import net.minecraft.entity.ai.attributes.{AbstractAttributeMap, IAttribute, IAttributeInstance}
import net.minecraft.entity.ai.{EntityJumpHelper, EntityLookHelper, EntityMoveHelper, EntitySenses}
import net.minecraft.entity.effect.EntityLightningBolt
import net.minecraft.entity.item.EntityItem
import net.minecraft.entity.player.{EntityPlayer, EntityPlayerMP}
import net.minecraft.inventory.EntityEquipmentSlot
import net.minecraft.item.{Item, ItemStack}
import net.minecraft.nbt.{NBTTagCompound, NBTTagList}
import net.minecraft.network.datasync.{DataParameter, EntityDataManager}
import net.minecraft.pathfinding.{PathNavigate, PathNodeType}
import net.minecraft.potion.{Potion, PotionEffect}
import net.minecraft.scoreboard.Team
import net.minecraft.server.MinecraftServer
import net.minecraft.util._
import net.minecraft.util.math.{AxisAlignedBB, BlockPos, RayTraceResult, Vec3d}
import net.minecraft.util.text.ITextComponent
import net.minecraft.util.text.event.HoverEvent
import net.minecraft.world.{DifficultyInstance, Explosion, World}
import net.minecraftforge.fml.common.registry.IEntityAdditionalSpawnData

trait SoulEntityLivingTrait extends EntityLiving with ISoulEntity with IEntityAdditionalSpawnData {

    var soul: ISoul
    val world: World

    val fieldLogic = new FieldLogic(this)
    val methodLogic = new MethodLogic(this)

    override def getSoul: ISoul = soul

    override def getVar[A](name: TypedName[A]): A = fieldLogic.getVar(name)
    override def setVar[A](name: TypedName[A], value: A): Unit = fieldLogic.setVar(name, value)
    override def makePersistent(name: TypedName[_]): Unit = fieldLogic.makePersistent(name)

    override def callMethod[A](name: TypedName[A], args: Any*): A = methodLogic.callMethod(name, () => null.asInstanceOf[A], args)


    override def writeSpawnData(data: ByteBuf) {
        val compound = new NBTTagCompound
        writeToNBT(compound)

        val bytes = UtilNBT.compoundToByteArray(compound)
        data.writeInt(bytes.length)
        data.writeBytes(bytes)
    }

    override def readSpawnData(data: ByteBuf) {
        val length = data.readInt
        val bytes = new Array[Byte](length)

        data.readBytes(bytes)

        val compound: NBTTagCompound = UtilNBT.byteArrayToCompound(bytes)
        readFromNBT(compound)
    }

    override def writeToNBT(compound: NBTTagCompound): Unit = {
        GIApiInterface.dataTypeRegistry.writeValueToNBT(compound, "soul", classOf[ISoul], soul)
        fieldLogic.writeToNBT(compound)
        methodLogic.callMethod(FunctionLib.FuncEntityWriteToNBT, () => super.writeToNBT(compound), compound)
    }

    override def readFromNBT(compound: NBTTagCompound): Unit = {
        soul = GIApiInterface.dataTypeRegistry.readValueFromNBT(compound, "soul", classOf[ISoul])
        fieldLogic.readFromNBT(compound)
        methodLogic.callMethod(FunctionLib.FuncEntityReadFromNBT, () => super.readFromNBT(compound), compound)
    }


    override def addChatMessage(component: ITextComponent): Unit = methodLogic.callMethod(FuncEntityAddChatMessage, () => super.addChatMessage(component), component)
    override def addEntityCrashInfo(category: CrashReportCategory): Unit = methodLogic.callMethod(FuncEntityAddEntityCrashInfo, () => super.addEntityCrashInfo(category), category)
    override def addPassenger(passenger: Entity): Unit = methodLogic.callMethod(FuncEntityAddPassenger, () => super.addPassenger(passenger), passenger)
    override def addTag(tag: String): Boolean = methodLogic.callMethod(FuncEntityAddTag, () => super.addTag(tag), tag)
    override def addToPlayerScore(entityIn: Entity, amount: Int): Unit = methodLogic.callMethod(FuncEntityAddToPlayerScore, () => super.addToPlayerScore(entityIn, amount), entityIn, amount)
    override def addVelocity(x: Double, y: Double, z: Double): Unit = methodLogic.callMethod(FuncEntityAddVelocity, () => super.addVelocity(x, y, z), x, y, z)
    override def applyEnchantments(entityLivingBaseIn: EntityLivingBase, entityIn: Entity): Unit = methodLogic.callMethod(FuncEntityApplyEnchantments, () => super.applyEnchantments(entityLivingBaseIn, entityIn), entityLivingBaseIn, entityIn)
    override def applyEntityCollision(entityIn: Entity): Unit = methodLogic.callMethod(FuncEntityApplyEntityCollision, () => super.applyEntityCollision(entityIn), entityIn)
    override def applyOrientationToEntity(entityToUpdate: Entity): Unit = methodLogic.callMethod(FuncEntityApplyOrientationToEntity, () => super.applyOrientationToEntity(entityToUpdate), entityToUpdate)
    override def applyPlayerInteraction(player: EntityPlayer, vec: Vec3d, stack: ItemStack, hand: EnumHand): EnumActionResult = methodLogic.callMethod(FuncEntityApplyPlayerInteraction, () => super.applyPlayerInteraction(player, vec, stack, hand), player, vec, stack, hand)
    override def attackEntityFrom(source: DamageSource, amount: Float): Boolean = methodLogic.callMethod(FuncEntityAttackEntityFrom, () => super.attackEntityFrom(source, amount), source, amount)
    override def canAttackWithItem: Boolean = methodLogic.callMethod(FuncEntityCanAttackWithItem, () => super.canAttackWithItem)
    override def canBeCollidedWith: Boolean = methodLogic.callMethod(FuncEntityCanBeCollidedWith, () => super.canBeCollidedWith)
    override def canBePushed: Boolean = methodLogic.callMethod(FuncEntityCanBePushed, () => super.canBePushed)
    override def canBeRidden(entityIn: Entity): Boolean = methodLogic.callMethod(FuncEntityCanBeRidden, () => super.canBeRidden(entityIn), entityIn)
    override def canCommandSenderUseCommand(permLevel: Int, commandName: String): Boolean = methodLogic.callMethod(FuncEntityCanCommandSenderUseCommand, () => super.canCommandSenderUseCommand(permLevel, commandName), permLevel, commandName)
    override def canFitPassenger(passenger: Entity): Boolean = methodLogic.callMethod(FuncEntityCanFitPassenger, () => super.canFitPassenger(passenger), passenger)
    override def canPassengerSteer: Boolean = methodLogic.callMethod(FuncEntityCanPassengerSteer, () => super.canPassengerSteer)
    override def canRenderOnFire: Boolean = methodLogic.callMethod(FuncEntityCanRenderOnFire, () => super.canRenderOnFire)
    override def canTriggerWalking: Boolean = methodLogic.callMethod(FuncEntityCanTriggerWalking, () => super.canTriggerWalking)
    override def changeDimension(dimensionIn: Int): Entity = methodLogic.callMethod(FuncEntityChangeDimension, () => super.changeDimension(dimensionIn), dimensionIn)
    override def copyLocationAndAnglesFrom(entityIn: Entity): Unit = methodLogic.callMethod(FuncEntityCopyLocationAndAnglesFrom, () => super.copyLocationAndAnglesFrom(entityIn), entityIn)
    override def createRunningParticles(): Unit = methodLogic.callMethod(FuncEntityCreateRunningParticles, () => super.createRunningParticles())
    override def dealFireDamage(amount: Int): Unit = methodLogic.callMethod(FuncEntityDealFireDamage, () => super.dealFireDamage(amount), amount)
    override def decrementTimeUntilPortal(): Unit = methodLogic.callMethod(FuncEntityDecrementTimeUntilPortal, () => super.decrementTimeUntilPortal())
    override def dismountRidingEntity(): Unit = methodLogic.callMethod(FuncEntityDismountRidingEntity, () => super.dismountRidingEntity())
    override def doBlockCollisions(): Unit = methodLogic.callMethod(FuncEntityDoBlockCollisions, () => super.doBlockCollisions())
    override def doesEntityNotTriggerPressurePlate(): Boolean = methodLogic.callMethod(FuncEntityDoesEntityNotTriggerPressurePlate, () => super.doesEntityNotTriggerPressurePlate())
    override def dropItem(itemIn: Item, size: Int): EntityItem = methodLogic.callMethod(FuncEntityDropItem, () => super.dropItem(itemIn, size), itemIn, size)
    override def dropItemWithOffset(itemIn: Item, size: Int, offsetY: Float): EntityItem = methodLogic.callMethod(FuncEntityDropItemWithOffset, () => super.dropItemWithOffset(itemIn, size, offsetY), itemIn, size, offsetY)
    override def entityDropItem(stack: ItemStack, offsetY: Float): EntityItem = methodLogic.callMethod(FuncEntityEntityDropItem, () => super.entityDropItem(stack, offsetY), stack, offsetY)
    override def entityInit(): Unit = methodLogic.callMethod(FuncEntityEntityInit, () => super.entityInit())
    override def equals(p_equals_1_ : Object): Boolean = methodLogic.callMethod(FuncEntityEquals, () => super.equals(p_equals_1_), p_equals_1_)
    override def extinguish(): Unit = methodLogic.callMethod(FuncEntityExtinguish, () => super.extinguish())
    override def fall(distance: Float, damageMultiplier: Float): Unit = methodLogic.callMethod(FuncEntityFall, () => super.fall(distance, damageMultiplier), distance, damageMultiplier)
    override def func_184213_bq(): Boolean = methodLogic.callMethod(FuncEntityFunc_184213_bq, () => super.func_184213_bq())
    override def getAdjustedHorizontalFacing: EnumFacing = methodLogic.callMethod(FuncEntityGetAdjustedHorizontalFacing, () => super.getAdjustedHorizontalFacing)
    override def getAir: Int = methodLogic.callMethod(FuncEntityGetAir, () => super.getAir)
    override def getAlwaysRenderNameTag: Boolean = methodLogic.callMethod(FuncEntityGetAlwaysRenderNameTag, () => super.getAlwaysRenderNameTag)
    override def getAlwaysRenderNameTagForRender: Boolean = methodLogic.callMethod(FuncEntityGetAlwaysRenderNameTagForRender, () => super.getAlwaysRenderNameTagForRender)
    override def getArmorInventoryList: lang.Iterable[ItemStack] = methodLogic.callMethod(FuncEntityGetArmorInventoryList, () => super.getArmorInventoryList)
    override def getBrightness(partialTicks: Float): Float = methodLogic.callMethod(FuncEntityGetBrightness, () => super.getBrightness(partialTicks), partialTicks)
    override def getBrightnessForRender(partialTicks: Float): Int = methodLogic.callMethod(FuncEntityGetBrightnessForRender, () => super.getBrightnessForRender(partialTicks), partialTicks)
    override def getCollisionBorderSize: Float = methodLogic.callMethod(FuncEntityGetCollisionBorderSize, () => super.getCollisionBorderSize)
    override def getCollisionBoundingBox: AxisAlignedBB = methodLogic.callMethod(FuncEntityGetCollisionBoundingBox, () => super.getCollisionBoundingBox)
    override def getCollisionBox(entityIn: Entity): AxisAlignedBB = methodLogic.callMethod(FuncEntityGetCollisionBox, () => super.getCollisionBox(entityIn), entityIn)
    override def getCommandSenderEntity: Entity = methodLogic.callMethod(FuncEntityGetCommandSenderEntity, () => super.getCommandSenderEntity)
    override def getCommandStats: CommandResultStats = methodLogic.callMethod(FuncEntityGetCommandStats, () => super.getCommandStats)
    override def getControllingPassenger: Entity = methodLogic.callMethod(FuncEntityGetControllingPassenger, () => super.getControllingPassenger)
    override def getCustomNameTag: String = methodLogic.callMethod(FuncEntityGetCustomNameTag, () => super.getCustomNameTag)
    override def getDataManager: EntityDataManager = methodLogic.callMethod(FuncEntityGetDataManager, () => super.getDataManager)
    override def getDisplayName: ITextComponent = methodLogic.callMethod(FuncEntityGetDisplayName, () => super.getDisplayName)
    override def getDistance(x: Double, y: Double, z: Double): Double = methodLogic.callMethod(FuncEntityGetDistance, () => super.getDistance(x, y, z), x, y, z)
    override def getDistanceSq(x: Double, y: Double, z: Double): Double = methodLogic.callMethod(FuncEntityGetDistanceSq_Coord, () => super.getDistanceSq(x, y, z), x, y, z)
    override def getDistanceSq(pos: BlockPos): Double = methodLogic.callMethod(FuncEntityGetDistanceSq_BlockPos, () => super.getDistanceSq(pos), pos)
    override def getDistanceSqToCenter(pos: BlockPos): Double = methodLogic.callMethod(FuncEntityGetDistanceSqToCenter, () => super.getDistanceSqToCenter(pos), pos)
    override def getDistanceSqToEntity(entityIn: Entity): Double = methodLogic.callMethod(FuncEntityGetDistanceSqToEntity, () => super.getDistanceSqToEntity(entityIn), entityIn)
    override def getDistanceToEntity(entityIn: Entity): Float = methodLogic.callMethod(FuncEntityGetDistanceToEntity, () => super.getDistanceToEntity(entityIn), entityIn)
    override def getEntityBoundingBox: AxisAlignedBB = methodLogic.callMethod(FuncEntityGetEntityBoundingBox, () => super.getEntityBoundingBox)
    override def getEntityId: Int = methodLogic.callMethod(FuncEntityGetEntityId, () => super.getEntityId)
    methodLogic.addFinalMethod(FuncEntityGetEntityString, (args: Seq[Any]) => super.getEntityString)
    override def getEntityWorld: World = methodLogic.callMethod(FuncEntityGetEntityWorld, () => super.getEntityWorld)
    override def getEquipmentAndArmor: lang.Iterable[ItemStack] = methodLogic.callMethod(FuncEntityGetEquipmentAndArmor, () => super.getEquipmentAndArmor)
    override def getExplosionResistance(explosionIn: Explosion, worldIn: World, pos: BlockPos, blockStateIn: IBlockState): Float = methodLogic.callMethod(FuncEntityGetExplosionResistance, () => super.getExplosionResistance(explosionIn, worldIn, pos, blockStateIn), explosionIn, worldIn, pos, blockStateIn)
    override def getEyeHeight: Float = methodLogic.callMethod(FuncEntityGetEyeHeight, () => super.getEyeHeight)
    override def getFlag(flag: Int): Boolean = methodLogic.callMethod(FuncEntityGetFlag, () => super.getFlag(flag), flag)
    override def getHeldEquipment: lang.Iterable[ItemStack] = methodLogic.callMethod(FuncEntityGetHeldEquipment, () => super.getHeldEquipment)
    override def getHorizontalFacing: EnumFacing = methodLogic.callMethod(FuncEntityGetHorizontalFacing, () => super.getHorizontalFacing)
    override def getHoverEvent: HoverEvent = methodLogic.callMethod(FuncEntityGetHoverEvent, () => super.getHoverEvent)
    override def getLastPortalVec: Vec3d = methodLogic.callMethod(FuncEntityGetLastPortalVec, () => super.getLastPortalVec)
    override def getLook(partialTicks: Float): Vec3d = methodLogic.callMethod(FuncEntityGetLook, () => super.getLook(partialTicks), partialTicks)
    override def getLookVec: Vec3d = methodLogic.callMethod(FuncEntityGetLookVec, () => super.getLookVec)
    override def getLowestRidingEntity: Entity = methodLogic.callMethod(FuncEntityGetLowestRidingEntity, () => super.getLowestRidingEntity)
    override def getMaxFallHeight: Int = methodLogic.callMethod(FuncEntityGetMaxFallHeight, () => super.getMaxFallHeight)
    override def getMaxInPortalTime: Int = methodLogic.callMethod(FuncEntityGetMaxInPortalTime, () => super.getMaxInPortalTime)
    override def getMirroredYaw(transformMirror: Mirror): Float = methodLogic.callMethod(FuncEntityGetMirroredYaw, () => super.getMirroredYaw(transformMirror), transformMirror)
    override def getMountedYOffset: Double = methodLogic.callMethod(FuncEntityGetMountedYOffset, () => super.getMountedYOffset)
    override def getName: String = methodLogic.callMethod(FuncEntityGetName, () => super.getName)
    override def getParts: Array[Entity] = methodLogic.callMethod(FuncEntityGetParts, () => super.getParts)
    override def getPassengers: util.List[Entity] = methodLogic.callMethod(FuncEntityGetPassengers, () => super.getPassengers)
    override def getPortalCooldown: Int = methodLogic.callMethod(FuncEntityGetPortalCooldown, () => super.getPortalCooldown)
    override def getPosition: BlockPos = methodLogic.callMethod(FuncEntityGetPosition, () => super.getPosition)
    override def getPositionEyes(partialTicks: Float): Vec3d = methodLogic.callMethod(FuncEntityGetPositionEyes, () => super.getPositionEyes(partialTicks), partialTicks)
    override def getPositionVector: Vec3d = methodLogic.callMethod(FuncEntityGetPositionVector, () => super.getPositionVector)
    override def getPushReaction: EnumPushReaction = methodLogic.callMethod(FuncEntityGetPushReaction, () => super.getPushReaction)
    override def getRecursivePassengers: util.Collection[Entity] = methodLogic.callMethod(FuncEntityGetRecursivePassengers, () => super.getRecursivePassengers)
    override def getRecursivePassengersByType[T <: Entity](entityClass: Class[T]): util.Collection[T] = methodLogic.callMethod(FuncEntityGetRecursivePassengersByType_Collection, () => super.getRecursivePassengersByType(entityClass), entityClass).asInstanceOf[util.Collection[T]]
    override def getRenderBoundingBox: AxisAlignedBB = methodLogic.callMethod(FuncEntityGetRenderBoundingBox, () => super.getRenderBoundingBox)
    override def getRidingEntity: Entity = methodLogic.callMethod(FuncEntityGetRidingEntity, () => super.getRidingEntity)
    override def getRotatedYaw(transformRotation: Rotation): Float = methodLogic.callMethod(FuncEntityGetRotatedYaw, () => super.getRotatedYaw(transformRotation), transformRotation)
    override def getRotationYawHead: Float = methodLogic.callMethod(FuncEntityGetRotationYawHead, () => super.getRotationYawHead)
    override def getServer: MinecraftServer = methodLogic.callMethod(FuncEntityGetServer, () => super.getServer)
    override def getSoundCategory: SoundCategory = methodLogic.callMethod(FuncEntityGetSoundCategory, () => super.getSoundCategory)
    override def getSplashSound: SoundEvent = methodLogic.callMethod(FuncEntityGetSplashSound, () => super.getSplashSound)
    override def getSwimSound: SoundEvent = methodLogic.callMethod(FuncEntityGetSwimSound, () => super.getSwimSound)
    override def getTags: util.Set[String] = methodLogic.callMethod(FuncEntityGetTags, () => super.getTags)
    override def getTeam: Team = methodLogic.callMethod(FuncEntityGetTeam, () => super.getTeam)
    override def getTeleportDirection: EnumFacing = methodLogic.callMethod(FuncEntityGetTeleportDirection, () => super.getTeleportDirection)
    override def getUniqueID: UUID = methodLogic.callMethod(FuncEntityGetUniqueID, () => super.getUniqueID)
    methodLogic.addFinalMethod(FuncEntityGetVectorForRotation, (args: Seq[Any]) => super.getVectorForRotation(args(0).asInstanceOf[Float], args(1).asInstanceOf[Float]))
    override def getYOffset: Double = methodLogic.callMethod(FuncEntityGetYOffset, () => super.getYOffset)
    override def handleStatusUpdate(id: Byte): Unit = methodLogic.callMethod(FuncEntityHandleStatusUpdate, () => super.handleStatusUpdate(id), id)
    override def handleWaterMovement(): Boolean = methodLogic.callMethod(FuncEntityHandleWaterMovement, () => super.handleWaterMovement())
    override def hasCustomName: Boolean = methodLogic.callMethod(FuncEntityHasCustomName, () => super.hasCustomName)
    override def hashCode(): Int = methodLogic.callMethod(FuncEntityHashCode, () => super.hashCode())
    override def hitByEntity(entityIn: Entity): Boolean = methodLogic.callMethod(FuncEntityHitByEntity, () => super.hitByEntity(entityIn), entityIn)
    override def isBeingRidden: Boolean = methodLogic.callMethod(FuncEntityIsBeingRidden, () => super.isBeingRidden)
    override def isBurning: Boolean = methodLogic.callMethod(FuncEntityIsBurning, () => super.isBurning)
    override def isEntityAlive: Boolean = methodLogic.callMethod(FuncEntityIsEntityAlive, () => super.isEntityAlive)
    override def isEntityEqual(entityIn: Entity): Boolean = methodLogic.callMethod(FuncEntityIsEntityEqual, () => super.isEntityEqual(entityIn), entityIn)
    override def isEntityInsideOpaqueBlock: Boolean = methodLogic.callMethod(FuncEntityIsEntityInsideOpaqueBlock, () => super.isEntityInsideOpaqueBlock)
    override def isEntityInvulnerable(source: DamageSource): Boolean = methodLogic.callMethod(FuncEntityIsEntityInvulnerable, () => super.isEntityInvulnerable(source), source)
    override def isGlowing: Boolean = methodLogic.callMethod(FuncEntityIsGlowing, () => super.isGlowing)
    override def isImmuneToExplosions: Boolean = methodLogic.callMethod(FuncEntityIsImmuneToExplosions, () => super.isImmuneToExplosions)
    methodLogic.addFinalMethod(FuncEntityIsImmuneToFire, (args: Seq[Any]) => super.isImmuneToFire)
    override def isInLava: Boolean = methodLogic.callMethod(FuncEntityIsInLava, () => super.isInLava)
    override def isInRangeToRender3d(x: Double, y: Double, z: Double): Boolean = methodLogic.callMethod(FuncEntityIsInRangeToRender3d, () => super.isInRangeToRender3d(x, y, z), x, y, z)
    override def isInRangeToRenderDist(distance: Double): Boolean = methodLogic.callMethod(FuncEntityIsInRangeToRenderDist, () => super.isInRangeToRenderDist(distance), distance)
    override def isInWater: Boolean = methodLogic.callMethod(FuncEntityIsInWater, () => super.isInWater)
    override def isInsideOfMaterial(materialIn: Material): Boolean = methodLogic.callMethod(FuncEntityIsInsideOfMaterial, () => super.isInsideOfMaterial(materialIn), materialIn)
    override def isInvisible: Boolean = methodLogic.callMethod(FuncEntityIsInvisible, () => super.isInvisible)
    override def isInvisibleToPlayer(player: EntityPlayer): Boolean = methodLogic.callMethod(FuncEntityIsInvisibleToPlayer, () => super.isInvisibleToPlayer(player), player)
    override def isNonBoss: Boolean = methodLogic.callMethod(FuncEntityIsNonBoss, () => super.isNonBoss)
    override def isOffsetPositionInLiquid(x: Double, y: Double, z: Double): Boolean = methodLogic.callMethod(FuncEntityIsOffsetPositionInLiquid, () => super.isOffsetPositionInLiquid(x, y, z), x, y, z)
    override def isOnSameTeam(entityIn: Entity): Boolean = methodLogic.callMethod(FuncEntityIsOnSameTeam, () => super.isOnSameTeam(entityIn), entityIn)
    override def isOnScoreboardTeam(teamIn: Team): Boolean = methodLogic.callMethod(FuncEntityIsOnScoreboardTeam, () => super.isOnScoreboardTeam(teamIn), teamIn)
    override def isOutsideBorder: Boolean = methodLogic.callMethod(FuncEntityIsOutsideBorder, () => super.isOutsideBorder)
    override def isPassenger(entityIn: Entity): Boolean = methodLogic.callMethod(FuncEntityIsPassenger, () => super.isPassenger(entityIn), entityIn)
    override def isPushedByWater: Boolean = methodLogic.callMethod(FuncEntityIsPushedByWater, () => super.isPushedByWater)
    override def isRiding: Boolean = methodLogic.callMethod(FuncEntityIsRiding, () => super.isRiding)
    override def isRidingOrBeingRiddenBy(entityIn: Entity): Boolean = methodLogic.callMethod(FuncEntityIsRidingOrBeingRiddenBy, () => super.isRidingOrBeingRiddenBy(entityIn), entityIn)
    override def isRidingSameEntity(entityIn: Entity): Boolean = methodLogic.callMethod(FuncEntityIsRidingSameEntity, () => super.isRidingSameEntity(entityIn), entityIn)
    override def isSilent: Boolean = methodLogic.callMethod(FuncEntityIsSilent, () => super.isSilent)
    override def isSneaking: Boolean = methodLogic.callMethod(FuncEntityIsSneaking, () => super.isSneaking)
    override def isSpectatedByPlayer(player: EntityPlayerMP): Boolean = methodLogic.callMethod(FuncEntityIsSpectatedByPlayer, () => super.isSpectatedByPlayer(player), player)
    override def isSprinting: Boolean = methodLogic.callMethod(FuncEntityIsSprinting, () => super.isSprinting)
    override def isWet: Boolean = methodLogic.callMethod(FuncEntityIsWet, () => super.isWet)
    override def kill(): Unit = methodLogic.callMethod(FuncEntityKill, () => super.kill())
    override def moveEntity(x: Double, y: Double, z: Double): Unit = methodLogic.callMethod(FuncEntityMoveEntity, () => super.moveEntity(x, y, z), x, y, z)
    override def moveFlying(strafe: Float, forward: Float, friction: Float): Unit = methodLogic.callMethod(FuncEntityMoveFlying, () => super.moveFlying(strafe, forward, friction), strafe, forward, friction)
    override def moveToBlockPosAndAngles(pos: BlockPos, rotationYawIn: Float, rotationPitchIn: Float): Unit = methodLogic.callMethod(FuncEntityMoveToBlockPosAndAngles, () => super.moveToBlockPosAndAngles(pos, rotationYawIn, rotationPitchIn), pos, rotationYawIn, rotationPitchIn)
    override def newDoubleNBTList(numbers: Double*): NBTTagList = methodLogic.callMethod(FuncEntityNewDoubleNBTList, () => super.newDoubleNBTList(numbers:_*), numbers)
    override def newFloatNBTList(numbers: Float*): NBTTagList = methodLogic.callMethod(FuncEntityNewFloatNBTList, () => super.newFloatNBTList(numbers:_*), numbers)
    override def notifyDataManagerChange(key: DataParameter[_]): Unit = methodLogic.callMethod(FuncEntityNotifyDataManagerChange, () => super.notifyDataManagerChange(key), key)
    override def onChunkLoad(): Unit = methodLogic.callMethod(FuncEntityOnChunkLoad, () => super.onChunkLoad())
    override def onCollideWithPlayer(entityIn: EntityPlayer): Unit = methodLogic.callMethod(FuncEntityOnCollideWithPlayer, () => super.onCollideWithPlayer(entityIn), entityIn)
    override def onEntityUpdate(): Unit = methodLogic.callMethod(FuncEntityOnEntityUpdate, () => super.onEntityUpdate())
    override def onKillCommand(): Unit = methodLogic.callMethod(FuncEntityOnKillCommand, () => super.onKillCommand())
    override def onKillEntity(entityLivingIn: EntityLivingBase): Unit = methodLogic.callMethod(FuncEntityOnKillEntity, () => super.onKillEntity(entityLivingIn), entityLivingIn)
    override def onStruckByLightning(lightningBolt: EntityLightningBolt): Unit = methodLogic.callMethod(FuncEntityOnStruckByLightning, () => super.onStruckByLightning(lightningBolt), lightningBolt)
    override def onUpdate(): Unit = methodLogic.callMethod(FuncEntityOnUpdate, () => super.onUpdate())
    override def performHurtAnimation(): Unit = methodLogic.callMethod(FuncEntityPerformHurtAnimation, () => super.performHurtAnimation())
    override def playSound(soundIn: SoundEvent, volume: Float, pitch: Float): Unit = methodLogic.callMethod(FuncEntityPlaySound, () => super.playSound(soundIn, volume, pitch), soundIn, volume, pitch)
    override def playStepSound(pos: BlockPos, blockIn: Block): Unit = methodLogic.callMethod(FuncEntityPlayStepSound, () => super.playStepSound(pos, blockIn), pos, blockIn)
    override def preparePlayerToSpawn(): Unit = methodLogic.callMethod(FuncEntityPreparePlayerToSpawn, () => super.preparePlayerToSpawn())
    methodLogic.addFinalMethod(FuncEntityProcessInitialInteract, (args: Seq[Any]) => super.processInitialInteract(args(0).asInstanceOf[EntityPlayer], args(1).asInstanceOf[ItemStack], args(2).asInstanceOf[EnumHand]))
    override def pushOutOfBlocks(x: Double, y: Double, z: Double): Boolean = methodLogic.callMethod(FuncEntityPushOutOfBlocks, () => super.pushOutOfBlocks(x, y, z), x, y, z)
    override def rayTrace(blockReachDistance: Double, partialTicks: Float): RayTraceResult = methodLogic.callMethod(FuncEntityRayTrace, () => super.rayTrace(blockReachDistance, partialTicks), blockReachDistance, partialTicks)
    override def readEntityFromNBT(var1: NBTTagCompound): Unit = methodLogic.callMethod(FuncEntityReadEntityFromNBT, () => super.readEntityFromNBT(var1), var1)
    override def removePassenger(passenger: Entity): Unit = methodLogic.callMethod(FuncEntityRemovePassenger, () => super.removePassenger(passenger), passenger)
    override def removePassengers(): Unit = methodLogic.callMethod(FuncEntityRemovePassengers, () => super.removePassengers())
    override def removeTag(tag: String): Boolean = methodLogic.callMethod(FuncEntityRemoveTag, () => super.removeTag(tag), tag)
    override def replaceItemInInventory(inventorySlot: Int, itemStackIn: ItemStack): Boolean = methodLogic.callMethod(FuncEntityReplaceItemInInventory, () => super.replaceItemInInventory(inventorySlot, itemStackIn), inventorySlot, itemStackIn)
    override def resetHeight(): Unit = methodLogic.callMethod(FuncEntityResetHeight, () => super.resetHeight())
    override def resetPositionToBB(): Unit = methodLogic.callMethod(FuncEntityResetPositionToBB, () => super.resetPositionToBB())
    override def sendCommandFeedback(): Boolean = methodLogic.callMethod(FuncEntitySendCommandFeedback, () => super.sendCommandFeedback())
    override def setAir(air: Int): Unit = methodLogic.callMethod(FuncEntitySetAir, () => super.setAir(air), air)
    override def setAlwaysRenderNameTag(alwaysRenderNameTag: Boolean): Unit = methodLogic.callMethod(FuncEntitySetAlwaysRenderNameTag, () => super.setAlwaysRenderNameTag(alwaysRenderNameTag), alwaysRenderNameTag)
    override def setAngles(yaw: Float, pitch: Float): Unit = methodLogic.callMethod(FuncEntitySetAngles, () => super.setAngles(yaw, pitch), yaw, pitch)
    override def setBeenAttacked(): Unit = methodLogic.callMethod(FuncEntitySetBeenAttacked, () => super.setBeenAttacked())
    override def setBossNonVisibleTo(player: EntityPlayerMP): Unit = methodLogic.callMethod(FuncEntitySetBossNonVisibleTo, () => super.setBossNonVisibleTo(player), player)
    override def setBossVisibleTo(player: EntityPlayerMP): Unit = methodLogic.callMethod(FuncEntitySetBossVisibleTo, () => super.setBossVisibleTo(player), player)
    override def setCommandStat(tpe: Type, amount: Int): Unit = methodLogic.callMethod(FuncEntitySetCommandStat, () => super.setCommandStat(tpe, amount), tpe, amount)
    override def setCommandStats(entityIn: Entity): Unit = methodLogic.callMethod(FuncEntitySetCommandStats, () => super.setCommandStats(entityIn), entityIn)
    override def setCustomNameTag(name: String): Unit = methodLogic.callMethod(FuncEntitySetCustomNameTag, () => super.setCustomNameTag(name), name)
    override def setDead(): Unit = methodLogic.callMethod(FuncEntitySetDead, () => super.setDead())
    override def setDropItemsWhenDead(dropWhenDead: Boolean): Unit = methodLogic.callMethod(FuncEntitySetDropItemsWhenDead, () => super.setDropItemsWhenDead(dropWhenDead), dropWhenDead)
    override def setEntityBoundingBox(bb: AxisAlignedBB): Unit = methodLogic.callMethod(FuncEntitySetEntityBoundingBox, () => super.setEntityBoundingBox(bb), bb)
    override def setEntityId(id: Int): Unit = methodLogic.callMethod(FuncEntitySetEntityId, () => super.setEntityId(id), id)
    override def setEntityInvulnerable(isInvulnerable: Boolean): Unit = methodLogic.callMethod(FuncEntitySetEntityInvulnerable, () => super.setEntityInvulnerable(isInvulnerable), isInvulnerable)
    override def setFire(seconds: Int): Unit = methodLogic.callMethod(FuncEntitySetFire, () => super.setFire(seconds), seconds)
    override def setFlag(flag: Int, set: Boolean): Unit = methodLogic.callMethod(FuncEntitySetFlag, () => super.setFlag(flag, set), flag, set)
    override def setGlowing(glowingIn: Boolean): Unit = methodLogic.callMethod(FuncEntitySetGlowing, () => super.setGlowing(glowingIn), glowingIn)
    override def setInWeb(): Unit = methodLogic.callMethod(FuncEntitySetInWeb, () => super.setInWeb())
    override def setInvisible(invisible: Boolean): Unit = methodLogic.callMethod(FuncEntitySetInvisible, () => super.setInvisible(invisible), invisible)
    override def setItemStackToSlot(slotIn: EntityEquipmentSlot, stack: ItemStack): Unit = methodLogic.callMethod(FuncEntitySetItemStackToSlot, () => super.setItemStackToSlot(slotIn, stack), slotIn, stack)
    override def setLocationAndAngles(x: Double, y: Double, z: Double, yaw: Float, pitch: Float): Unit = methodLogic.callMethod(FuncEntitySetLocationAndAngles, () => super.setLocationAndAngles(x, y, z, yaw, pitch), x, y, z, yaw, pitch)
    override def setOnFireFromLava(): Unit = methodLogic.callMethod(FuncEntitySetOnFireFromLava, () => super.setOnFireFromLava())
    override def setOutsideBorder(outsideBorder: Boolean): Unit = methodLogic.callMethod(FuncEntitySetOutsideBorder, () => super.setOutsideBorder(outsideBorder), outsideBorder)
    override def setPortal(pos: BlockPos): Unit = methodLogic.callMethod(FuncEntitySetPortal, () => super.setPortal(pos), pos)
    override def setPosition(x: Double, y: Double, z: Double): Unit = methodLogic.callMethod(FuncEntitySetPosition, () => super.setPosition(x, y, z), x, y, z)
    override def setPositionAndRotation(x: Double, y: Double, z: Double, yaw: Float, pitch: Float): Unit = methodLogic.callMethod(FuncEntitySetPositionAndRotation, () => super.setPositionAndRotation(x, y, z, yaw, pitch), x, y, z, yaw, pitch)
    override def setPositionAndRotation2(x: Double, y: Double, z: Double, yaw: Float, pitch: Float, posRotationIncrements: Int, teleport: Boolean): Unit = methodLogic.callMethod(FuncEntitySetPositionAndRotation2, () => super.setPositionAndRotation2(x, y, z, yaw, pitch, posRotationIncrements, teleport), x, y, z, yaw, pitch, posRotationIncrements, teleport)
    override def setPositionAndUpdate(x: Double, y: Double, z: Double): Unit = methodLogic.callMethod(FuncEntitySetPositionAndUpdate, () => super.setPositionAndUpdate(x, y, z), x, y, z)
    override def setPositionNonDirty(): Boolean = methodLogic.callMethod(FuncEntitySetPositionNonDirty, () => super.setPositionNonDirty())
    override def setRenderYawOffset(offset: Float): Unit = methodLogic.callMethod(FuncEntitySetRenderYawOffset, () => super.setRenderYawOffset(offset), offset)
    override def setRotation(yaw: Float, pitch: Float): Unit = methodLogic.callMethod(FuncEntitySetRotation, () => super.setRotation(yaw, pitch), yaw, pitch)
    override def setRotationYawHead(rotation: Float): Unit = methodLogic.callMethod(FuncEntitySetRotationYawHead, () => super.setRotationYawHead(rotation), rotation)
    override def setSilent(isSilent: Boolean): Unit = methodLogic.callMethod(FuncEntitySetSilent, () => super.setSilent(isSilent), isSilent)
    override def setSize(width: Float, height: Float): Unit = methodLogic.callMethod(FuncEntitySetSize, () => super.setSize(width, height), width, height)
    override def setSneaking(sneaking: Boolean): Unit = methodLogic.callMethod(FuncEntitySetSneaking, () => super.setSneaking(sneaking), sneaking)
    override def setSprinting(sprinting: Boolean): Unit = methodLogic.callMethod(FuncEntitySetSprinting, () => super.setSprinting(sprinting), sprinting)
    override def setUniqueId(uniqueIdIn: UUID): Unit = methodLogic.callMethod(FuncEntitySetUniqueId, () => super.setUniqueId(uniqueIdIn), uniqueIdIn)
    override def setVelocity(x: Double, y: Double, z: Double): Unit = methodLogic.callMethod(FuncEntitySetVelocity, () => super.setVelocity(x, y, z), x, y, z)
    override def setWorld(worldIn: World): Unit = methodLogic.callMethod(FuncEntitySetWorld, () => super.setWorld(worldIn), worldIn)
    override def shouldSetPosAfterLoading(): Boolean = methodLogic.callMethod(FuncEntityShouldSetPosAfterLoading, () => super.shouldSetPosAfterLoading())
    override def spawnRunningParticles(): Unit = methodLogic.callMethod(FuncEntitySpawnRunningParticles, () => super.spawnRunningParticles())
    override def startRiding(entityIn: Entity): Boolean = methodLogic.callMethod(FuncEntityStartRiding_OneParam, () => super.startRiding(entityIn), entityIn)
    override def startRiding(entityIn: Entity, force: Boolean): Boolean = methodLogic.callMethod(FuncEntityStartRiding_TwoParam, () => super.startRiding(entityIn, force), entityIn, force)
    override def toString: String = methodLogic.callMethod(FuncEntityToString, () => super.toString)
    override def updateFallState(y: Double, onGroundIn: Boolean, state: IBlockState, pos: BlockPos): Unit = methodLogic.callMethod(FuncEntityUpdateFallState, () => super.updateFallState(y, onGroundIn, state, pos), y, onGroundIn, state, pos)
    override def updatePassenger(passenger: Entity): Unit = methodLogic.callMethod(FuncEntityUpdatePassenger, () => super.updatePassenger(passenger), passenger)
    override def updateRidden(): Unit = methodLogic.callMethod(FuncEntityUpdateRidden, () => super.updateRidden())
    override def verifyExplosion(explosionIn: Explosion, worldIn: World, pos: BlockPos, blockStateIn: IBlockState, p_174816_5_ : Float): Boolean = methodLogic.callMethod(FuncEntityVerifyExplosion, () => super.verifyExplosion(explosionIn, worldIn, pos, blockStateIn, p_174816_5_), explosionIn, worldIn, pos, blockStateIn, p_174816_5_)
    override def writeEntityToNBT(var1: NBTTagCompound): Unit = methodLogic.callMethod(FuncEntityWriteEntityToNBT, () => super.writeEntityToNBT(var1), var1)
    override def writeToNBTAtomically(compound: NBTTagCompound): Boolean = methodLogic.callMethod(FuncEntityWriteToNBTAtomically, () => super.writeToNBTAtomically(compound), compound)
    override def writeToNBTOptional(compound: NBTTagCompound): Boolean = methodLogic.callMethod(FuncEntityWriteToNBTOptional, () => super.writeToNBTOptional(compound), compound)
    override def canAttackClass(cls: Class[_ <: EntityLivingBase]): Boolean = methodLogic.callMethod(FuncEntityLivingCanAttackClass, () => super.canAttackClass(cls), cls)
    override def canBeLeashedTo(player: EntityPlayer): Boolean = methodLogic.callMethod(FuncEntityLivingCanBeLeashedTo, () => super.canBeLeashedTo(player), player)
    override def canBeSteered: Boolean = methodLogic.callMethod(FuncEntityLivingCanBeSteered, () => super.canBeSteered)
    override def canDespawn: Boolean = methodLogic.callMethod(FuncEntityLivingCanDespawn, () => super.canDespawn)
    override def canEquipItem(stack: ItemStack): Boolean = methodLogic.callMethod(FuncEntityLivingCanEquipItem, () => super.canEquipItem(stack), stack)
    override def canPickUpLoot: Boolean = methodLogic.callMethod(FuncEntityLivingCanPickUpLoot, () => super.canPickUpLoot)
    override def clearLeashed(sendPacket: Boolean, dropLead: Boolean): Unit = methodLogic.callMethod(FuncEntityLivingClearLeashed, () => super.clearLeashed(sendPacket, dropLead), sendPacket, dropLead)
    override def createBodyHelper(): EntityBodyHelper = methodLogic.callMethod(FuncEntityLivingCreateBodyHelper, () => super.createBodyHelper())
    override def despawnEntity(): Unit = methodLogic.callMethod(FuncEntityLivingDespawnEntity, () => super.despawnEntity())
    override def eatGrassBonus(): Unit = methodLogic.callMethod(FuncEntityLivingEatGrassBonus, () => super.eatGrassBonus())
    override def enablePersistence(): Unit = methodLogic.callMethod(FuncEntityLivingEnablePersistence, () => super.enablePersistence())
    override def faceEntity(entityIn: Entity, maxYawIncrease: Float, maxPitchIncrease: Float): Unit = methodLogic.callMethod(FuncEntityLivingFaceEntity, () => super.faceEntity(entityIn, maxYawIncrease, maxPitchIncrease), entityIn, maxYawIncrease, maxPitchIncrease)
    override def getAmbientSound: SoundEvent = methodLogic.callMethod(FuncEntityLivingGetAmbientSound, () => super.getAmbientSound)
    override def getAttackTarget: EntityLivingBase = methodLogic.callMethod(FuncEntityLivingGetAttackTarget, () => super.getAttackTarget)
    override def getCanSpawnHere: Boolean = methodLogic.callMethod(FuncEntityLivingGetCanSpawnHere, () => super.getCanSpawnHere)
    override def getDropItem: Item = methodLogic.callMethod(FuncEntityLivingGetDropItem, () => super.getDropItem)
    override def getEntitySenses: EntitySenses = methodLogic.callMethod(FuncEntityLivingGetEntitySenses, () => super.getEntitySenses)
    override def getHorizontalFaceSpeed: Int = methodLogic.callMethod(FuncEntityLivingGetHorizontalFaceSpeed, () => super.getHorizontalFaceSpeed)
    override def getJumpHelper: EntityJumpHelper = methodLogic.callMethod(FuncEntityLivingGetJumpHelper, () => super.getJumpHelper)
    override def getLeashed: Boolean = methodLogic.callMethod(FuncEntityLivingGetLeashed, () => super.getLeashed)
    override def getLeashedToEntity: Entity = methodLogic.callMethod(FuncEntityLivingGetLeashedToEntity, () => super.getLeashedToEntity)
    override def getLookHelper: EntityLookHelper = methodLogic.callMethod(FuncEntityLivingGetLookHelper, () => super.getLookHelper)
    override def getLootTable: ResourceLocation = methodLogic.callMethod(FuncEntityLivingGetLootTable, () => super.getLootTable)
    override def getMaxSpawnedInChunk: Int = methodLogic.callMethod(FuncEntityLivingGetMaxSpawnedInChunk, () => super.getMaxSpawnedInChunk)
    override def getMoveHelper: EntityMoveHelper = methodLogic.callMethod(FuncEntityLivingGetMoveHelper, () => super.getMoveHelper)
    override def getNavigator: PathNavigate = methodLogic.callMethod(FuncEntityLivingGetNavigator, () => super.getNavigator)
    override def getNewNavigator(worldIn: World): PathNavigate = methodLogic.callMethod(FuncEntityLivingGetNewNavigator, () => super.getNewNavigator(worldIn), worldIn)
    override def getPathPriority(nodeType: PathNodeType): Float = methodLogic.callMethod(FuncEntityLivingGetPathPriority, () => super.getPathPriority(nodeType), nodeType)
    override def getRenderSizeModifier: Float = methodLogic.callMethod(FuncEntityLivingGetRenderSizeModifier, () => super.getRenderSizeModifier)
    override def getTalkInterval: Int = methodLogic.callMethod(FuncEntityLivingGetTalkInterval, () => super.getTalkInterval)
    override def getVerticalFaceSpeed: Int = methodLogic.callMethod(FuncEntityLivingGetVerticalFaceSpeed, () => super.getVerticalFaceSpeed)
    override def initEntityAI(): Unit = methodLogic.callMethod(FuncEntityLivingInitEntityAI, () => super.initEntityAI())
    override def isAIDisabled: Boolean = methodLogic.callMethod(FuncEntityLivingIsAIDisabled, () => super.isAIDisabled)
    override def isLeftHanded: Boolean = methodLogic.callMethod(FuncEntityLivingIsLeftHanded, () => super.isLeftHanded)
    override def isNoDespawnRequired: Boolean = methodLogic.callMethod(FuncEntityLivingIsNoDespawnRequired, () => super.isNoDespawnRequired)
    override def isNotColliding: Boolean = methodLogic.callMethod(FuncEntityLivingIsNotColliding, () => super.isNotColliding)
    override def onInitialSpawn(difficulty: DifficultyInstance, livingdata: IEntityLivingData): IEntityLivingData = methodLogic.callMethod(FuncEntityLivingOnInitialSpawn, () => super.onInitialSpawn(difficulty, livingdata), difficulty, livingdata)
    override def playLivingSound(): Unit = methodLogic.callMethod(FuncEntityLivingPlayLivingSound, () => super.playLivingSound())
    override def processInteract(player: EntityPlayer, hand: EnumHand, stack: ItemStack): Boolean = methodLogic.callMethod(FuncEntityLivingProcessInteract, () => super.processInteract(player, hand, stack), player, hand, stack)
    override def setAttackTarget(entitylivingbaseIn: EntityLivingBase): Unit = methodLogic.callMethod(FuncEntityLivingSetAttackTarget, () => super.setAttackTarget(entitylivingbaseIn), entitylivingbaseIn)
    override def setCanPickUpLoot(canPickup: Boolean): Unit = methodLogic.callMethod(FuncEntityLivingSetCanPickUpLoot, () => super.setCanPickUpLoot(canPickup), canPickup)
    override def setDropChance(slotIn: EntityEquipmentSlot, chance: Float): Unit = methodLogic.callMethod(FuncEntityLivingSetDropChance, () => super.setDropChance(slotIn, chance), slotIn, chance)
    override def setEnchantmentBasedOnDifficulty(difficulty: DifficultyInstance): Unit = methodLogic.callMethod(FuncEntityLivingSetEnchantmentBasedOnDifficulty, () => super.setEnchantmentBasedOnDifficulty(difficulty), difficulty)
    override def setEquipmentBasedOnDifficulty(difficulty: DifficultyInstance): Unit = methodLogic.callMethod(FuncEntityLivingSetEquipmentBasedOnDifficulty, () => super.setEquipmentBasedOnDifficulty(difficulty), difficulty)
    override def setLeashedToEntity(entityIn: Entity, sendAttachNotification: Boolean): Unit = methodLogic.callMethod(FuncEntityLivingSetLeashedToEntity, () => super.setLeashedToEntity(entityIn, sendAttachNotification), entityIn, sendAttachNotification)
    override def setLeftHanded(disable: Boolean): Unit = methodLogic.callMethod(FuncEntityLivingSetLeftHanded, () => super.setLeftHanded(disable), disable)
    override def setMoveForward(amount: Float): Unit = methodLogic.callMethod(FuncEntityLivingSetMoveForward, () => super.setMoveForward(amount), amount)
    override def setMoveStrafing(amount: Float): Unit = methodLogic.callMethod(FuncEntityLivingSetMoveStrafing, () => super.setMoveStrafing(amount), amount)
    override def setNoAI(disable: Boolean): Unit = methodLogic.callMethod(FuncEntityLivingSetNoAI, () => super.setNoAI(disable), disable)
    override def setPathPriority(nodeType: PathNodeType, priority: Float): Unit = methodLogic.callMethod(FuncEntityLivingSetPathPriority, () => super.setPathPriority(nodeType, priority), nodeType, priority)
    override def spawnExplosionParticle(): Unit = methodLogic.callMethod(FuncEntityLivingSpawnExplosionParticle, () => super.spawnExplosionParticle())
    override def updateAITasks(): Unit = methodLogic.callMethod(FuncEntityLivingUpdateAITasks, () => super.updateAITasks())
    override def updateEquipmentIfNeeded(itemEntity: EntityItem): Unit = methodLogic.callMethod(FuncEntityLivingUpdateEquipmentIfNeeded, () => super.updateEquipmentIfNeeded(itemEntity), itemEntity)
    override def updateLeashedState(): Unit = methodLogic.callMethod(FuncEntityLivingUpdateLeashedState, () => super.updateLeashedState())
    override def addPotionEffect(potioneffectIn: PotionEffect): Unit = methodLogic.callMethod(FuncEntityLivingBaseAddPotionEffect, () => super.addPotionEffect(potioneffectIn), potioneffectIn)
    override def applyArmorCalculations(source: DamageSource, damage: Float): Float = methodLogic.callMethod(FuncEntityLivingBaseApplyArmorCalculations, () => super.applyArmorCalculations(source, damage), source, damage)
    override def applyEntityAttributes(): Unit = methodLogic.callMethod(FuncEntityLivingBaseApplyEntityAttributes, () => super.applyEntityAttributes())
    override def applyPotionDamageCalculations(source: DamageSource, damage: Float): Float = methodLogic.callMethod(FuncEntityLivingBaseApplyPotionDamageCalculations, () => super.applyPotionDamageCalculations(source, damage), source, damage)
    override def attackEntityAsMob(entityIn: Entity): Boolean = methodLogic.callMethod(FuncEntityLivingBaseAttackEntityAsMob, () => super.attackEntityAsMob(entityIn), entityIn)
    override def canBeHitWithPotion: Boolean = methodLogic.callMethod(FuncEntityLivingBaseCanBeHitWithPotion, () => super.canBeHitWithPotion)
    override def canBreatheUnderwater: Boolean = methodLogic.callMethod(FuncEntityLivingBaseCanBreatheUnderwater, () => super.canBreatheUnderwater)
    override def canDropLoot: Boolean = methodLogic.callMethod(FuncEntityLivingBaseCanDropLoot, () => super.canDropLoot)
    override def canEntityBeSeen(entityIn: Entity): Boolean = methodLogic.callMethod(FuncEntityLivingBaseCanEntityBeSeen, () => super.canEntityBeSeen(entityIn), entityIn)
    override def clearActivePotions(): Unit = methodLogic.callMethod(FuncEntityLivingBaseClearActivePotions, () => super.clearActivePotions())
    override def collideWithEntity(entityIn: Entity): Unit = methodLogic.callMethod(FuncEntityLivingBaseCollideWithEntity, () => super.collideWithEntity(entityIn), entityIn)
    override def collideWithNearbyEntities(): Unit = methodLogic.callMethod(FuncEntityLivingBaseCollideWithNearbyEntities, () => super.collideWithNearbyEntities())
    override def damageArmor(damage: Float): Unit = methodLogic.callMethod(FuncEntityLivingBaseDamageArmor, () => super.damageArmor(damage), damage)
    override def damageEntity(damageSrc: DamageSource, damageAmount: Float): Unit = methodLogic.callMethod(FuncEntityLivingBaseDamageEntity, () => super.damageEntity(damageSrc, damageAmount), damageSrc, damageAmount)
    override def damageShield(damage: Float): Unit = methodLogic.callMethod(FuncEntityLivingBaseDamageShield, () => super.damageShield(damage), damage)
    override def decreaseAirSupply(air: Int): Int = methodLogic.callMethod(FuncEntityLivingBaseDecreaseAirSupply, () => super.decreaseAirSupply(air), air)
    override def dismountEntity(entityIn: Entity): Unit = methodLogic.callMethod(FuncEntityLivingBaseDismountEntity, () => super.dismountEntity(entityIn), entityIn)
    override def dropEquipment(wasRecentlyHit: Boolean, lootingModifier: Int): Unit = methodLogic.callMethod(FuncEntityLivingBaseDropEquipment, () => super.dropEquipment(wasRecentlyHit, lootingModifier), wasRecentlyHit, lootingModifier)
    override def dropFewItems(wasRecentlyHit: Boolean, lootingModifier: Int): Unit = methodLogic.callMethod(FuncEntityLivingBaseDropFewItems, () => super.dropFewItems(wasRecentlyHit, lootingModifier), wasRecentlyHit, lootingModifier)
    override def dropLoot(wasRecentlyHit: Boolean, lootingModifier: Int, source: DamageSource): Unit = methodLogic.callMethod(FuncEntityLivingBaseDropLoot, () => super.dropLoot(wasRecentlyHit, lootingModifier, source), wasRecentlyHit, lootingModifier, source)
    override def frostWalk(pos: BlockPos): Unit = methodLogic.callMethod(FuncEntityLivingBaseFrostWalk, () => super.frostWalk(pos), pos)
    override def getAIMoveSpeed: Float = methodLogic.callMethod(FuncEntityLivingBaseGetAIMoveSpeed, () => super.getAIMoveSpeed)
    override def getAITarget: EntityLivingBase = methodLogic.callMethod(FuncEntityLivingBaseGetAITarget, () => super.getAITarget)
    override def getAbsorptionAmount: Float = methodLogic.callMethod(FuncEntityLivingBaseGetAbsorptionAmount, () => super.getAbsorptionAmount)
    override def getActiveHand: EnumHand = methodLogic.callMethod(FuncEntityLivingBaseGetActiveHand, () => super.getActiveHand)
    override def getActiveItemStack: ItemStack = methodLogic.callMethod(FuncEntityLivingBaseGetActiveItemStack, () => super.getActiveItemStack)
    override def getActivePotionEffect(potionIn: Potion): PotionEffect = methodLogic.callMethod(FuncEntityLivingBaseGetActivePotionEffect, () => super.getActivePotionEffect(potionIn), potionIn)
    override def getActivePotionEffects: util.Collection[PotionEffect] = methodLogic.callMethod(FuncEntityLivingBaseGetActivePotionEffects, () => super.getActivePotionEffects)
    override def getAge: Int = methodLogic.callMethod(FuncEntityLivingBaseGetAge, () => super.getAge)
    methodLogic.addFinalMethod(FuncEntityLivingBaseGetArrowCountInEntity, (args: Seq[Any]) => super.getArrowCountInEntity)
    override def getAttackingEntity: EntityLivingBase = methodLogic.callMethod(FuncEntityLivingBaseGetAttackingEntity, () => super.getAttackingEntity)
    override def getAttributeMap: AbstractAttributeMap = methodLogic.callMethod(FuncEntityLivingBaseGetAttributeMap, () => super.getAttributeMap)
    override def getCombatTracker: CombatTracker = methodLogic.callMethod(FuncEntityLivingBaseGetCombatTracker, () => super.getCombatTracker)
    override def getCreatureAttribute: EnumCreatureAttribute = methodLogic.callMethod(FuncEntityLivingBaseGetCreatureAttribute, () => super.getCreatureAttribute)
    override def getDeathSound: SoundEvent = methodLogic.callMethod(FuncEntityLivingBaseGetDeathSound, () => super.getDeathSound)
    override def getEntityAttribute(attribute: IAttribute): IAttributeInstance = methodLogic.callMethod(FuncEntityLivingBaseGetEntityAttribute, () => super.getEntityAttribute(attribute), attribute)
    override def getExperiencePoints(player: EntityPlayer): Int = methodLogic.callMethod(FuncEntityLivingBaseGetExperiencePoints, () => super.getExperiencePoints(player), player)
    override def getFallSound(heightIn: Int): SoundEvent = methodLogic.callMethod(FuncEntityLivingBaseGetFallSound, () => super.getFallSound(heightIn), heightIn)
    methodLogic.addFinalMethod(FuncEntityLivingBaseGetHealth, (args: Seq[Any]) => super.getHealth)
    override def getHeldItem(hand: EnumHand): ItemStack = methodLogic.callMethod(FuncEntityLivingBaseGetHeldItem, () => super.getHeldItem(hand), hand)
    override def getHeldItemMainhand: ItemStack = methodLogic.callMethod(FuncEntityLivingBaseGetHeldItemMainhand, () => super.getHeldItemMainhand)
    override def getHeldItemOffhand: ItemStack = methodLogic.callMethod(FuncEntityLivingBaseGetHeldItemOffhand, () => super.getHeldItemOffhand)
    override def getHurtSound: SoundEvent = methodLogic.callMethod(FuncEntityLivingBaseGetHurtSound, () => super.getHurtSound)
    override def getItemInUseCount: Int = methodLogic.callMethod(FuncEntityLivingBaseGetItemInUseCount, () => super.getItemInUseCount)
    override def getItemInUseMaxCount: Int = methodLogic.callMethod(FuncEntityLivingBaseGetItemInUseMaxCount, () => super.getItemInUseMaxCount)
    override def getItemStackFromSlot(var1: EntityEquipmentSlot): ItemStack = methodLogic.callMethod(FuncEntityLivingBaseGetItemStackFromSlot, () => super.getItemStackFromSlot(var1), var1)
    override def getJumpUpwardsMotion: Float = methodLogic.callMethod(FuncEntityLivingBaseGetJumpUpwardsMotion, () => super.getJumpUpwardsMotion)
    override def getLastAttacker: EntityLivingBase = methodLogic.callMethod(FuncEntityLivingBaseGetLastAttacker, () => super.getLastAttacker)
    override def getLastAttackerTime: Int = methodLogic.callMethod(FuncEntityLivingBaseGetLastAttackerTime, () => super.getLastAttackerTime)
    methodLogic.addFinalMethod(FuncEntityLivingBaseGetMaxHealth, (args: Seq[Any]) => super.getMaxHealth)
    override def getPrimaryHand: EnumHandSide = methodLogic.callMethod(FuncEntityLivingBaseGetPrimaryHand, () => super.getPrimaryHand)
    override def getRNG: Random = methodLogic.callMethod(FuncEntityLivingBaseGetRNG, () => super.getRNG)
    override def getRevengeTimer: Int = methodLogic.callMethod(FuncEntityLivingBaseGetRevengeTimer, () => super.getRevengeTimer)
    override def getSoundPitch: Float = methodLogic.callMethod(FuncEntityLivingBaseGetSoundPitch, () => super.getSoundPitch)
    override def getSoundVolume: Float = methodLogic.callMethod(FuncEntityLivingBaseGetSoundVolume, () => super.getSoundVolume)
    override def getSwingProgress(partialTickTime: Float): Float = methodLogic.callMethod(FuncEntityLivingBaseGetSwingProgress, () => super.getSwingProgress(partialTickTime), partialTickTime)
    override def getTicksElytraFlying: Int = methodLogic.callMethod(FuncEntityLivingBaseGetTicksElytraFlying, () => super.getTicksElytraFlying)
    override def getTotalArmorValue: Int = methodLogic.callMethod(FuncEntityLivingBaseGetTotalArmorValue, () => super.getTotalArmorValue)
    override def handleJumpLava(): Unit = methodLogic.callMethod(FuncEntityLivingBaseHandleJumpLava, () => super.handleJumpLava())
    override def heal(healAmount: Float): Unit = methodLogic.callMethod(FuncEntityLivingBaseHeal, () => super.heal(healAmount), healAmount)
    override def isActiveItemStackBlocking: Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsActiveItemStackBlocking, () => super.isActiveItemStackBlocking)
    override def isChild: Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsChild, () => super.isChild)
    override def isElytraFlying: Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsElytraFlying, () => super.isElytraFlying)
    override def isEntityUndead: Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsEntityUndead, () => super.isEntityUndead)
    override def isHandActive: Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsHandActive, () => super.isHandActive)
    override def isMovementBlocked: Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsMovementBlocked, () => super.isMovementBlocked)
    override def isOnLadder: Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsOnLadder, () => super.isOnLadder)
    override def isPlayer: Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsPlayer, () => super.isPlayer)
    override def isPlayerSleeping: Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsPlayerSleeping, () => super.isPlayerSleeping)
    override def isPotionActive(potionIn: Potion): Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsPotionActive, () => super.isPotionActive(potionIn), potionIn)
    override def isPotionApplicable(potioneffectIn: PotionEffect): Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsPotionApplicable, () => super.isPotionApplicable(potioneffectIn), potioneffectIn)
    override def isServerWorld: Boolean = methodLogic.callMethod(FuncEntityLivingBaseIsServerWorld, () => super.isServerWorld)
    override def jump(): Unit = methodLogic.callMethod(FuncEntityLivingBaseJump, () => super.jump())
    override def knockBack(entityIn: Entity, strength: Float, xRatio: Double, zRatio: Double): Unit = methodLogic.callMethod(FuncEntityLivingBaseKnockBack, () => super.knockBack(entityIn, strength, xRatio, zRatio), entityIn, strength, xRatio, zRatio)
    override def markPotionsDirty(): Unit = methodLogic.callMethod(FuncEntityLivingBaseMarkPotionsDirty, () => super.markPotionsDirty())
    override def moveEntityWithHeading(strafe: Float, forward: Float): Unit = methodLogic.callMethod(FuncEntityLivingBaseMoveEntityWithHeading, () => super.moveEntityWithHeading(strafe, forward), strafe, forward)
    override def onChangedPotionEffect(id: PotionEffect, p_70695_2_ : Boolean): Unit = methodLogic.callMethod(FuncEntityLivingBaseOnChangedPotionEffect, () => super.onChangedPotionEffect(id, p_70695_2_), id, p_70695_2_)
    override def onDeath(cause: DamageSource): Unit = methodLogic.callMethod(FuncEntityLivingBaseOnDeath, () => super.onDeath(cause), cause)
    override def onDeathUpdate(): Unit = methodLogic.callMethod(FuncEntityLivingBaseOnDeathUpdate, () => super.onDeathUpdate())
    override def onFinishedPotionEffect(effect: PotionEffect): Unit = methodLogic.callMethod(FuncEntityLivingBaseOnFinishedPotionEffect, () => super.onFinishedPotionEffect(effect), effect)
    override def onItemPickup(entityIn: Entity, quantity: Int): Unit = methodLogic.callMethod(FuncEntityLivingBaseOnItemPickup, () => super.onItemPickup(entityIn, quantity), entityIn, quantity)
    override def onItemUseFinish(): Unit = methodLogic.callMethod(FuncEntityLivingBaseOnItemUseFinish, () => super.onItemUseFinish())
    override def onLivingUpdate(): Unit = methodLogic.callMethod(FuncEntityLivingBaseOnLivingUpdate, () => super.onLivingUpdate())
    override def onNewPotionEffect(id: PotionEffect): Unit = methodLogic.callMethod(FuncEntityLivingBaseOnNewPotionEffect, () => super.onNewPotionEffect(id), id)
    override def playEquipSound(stack: ItemStack): Unit = methodLogic.callMethod(FuncEntityLivingBasePlayEquipSound, () => super.playEquipSound(stack), stack)
    override def playHurtSound(source: DamageSource): Unit = methodLogic.callMethod(FuncEntityLivingBasePlayHurtSound, () => super.playHurtSound(source), source)
    override def removeActivePotionEffect(potioneffectin: Potion): PotionEffect = methodLogic.callMethod(FuncEntityLivingBaseRemoveActivePotionEffect, () => super.removeActivePotionEffect(potioneffectin), potioneffectin)
    override def removePotionEffect(p_184589_1_ : Potion): Unit = methodLogic.callMethod(FuncEntityLivingBaseRemovePotionEffect, () => super.removePotionEffect(p_184589_1_), p_184589_1_)
    override def renderBrokenItemStack(stack: ItemStack): Unit = methodLogic.callMethod(FuncEntityLivingBaseRenderBrokenItemStack, () => super.renderBrokenItemStack(stack), stack)
    override def resetActiveHand(): Unit = methodLogic.callMethod(FuncEntityLivingBaseResetActiveHand, () => super.resetActiveHand())
    override def resetPotionEffectMetadata(): Unit = methodLogic.callMethod(FuncEntityLivingBaseResetPotionEffectMetadata, () => super.resetPotionEffectMetadata())
    override def sendEndCombat(): Unit = methodLogic.callMethod(FuncEntityLivingBaseSendEndCombat, () => super.sendEndCombat())
    override def sendEnterCombat(): Unit = methodLogic.callMethod(FuncEntityLivingBaseSendEnterCombat, () => super.sendEnterCombat())
    override def setAIMoveSpeed(speedIn: Float): Unit = methodLogic.callMethod(FuncEntityLivingBaseSetAIMoveSpeed, () => super.setAIMoveSpeed(speedIn), speedIn)
    override def setAbsorptionAmount(amount: Float): Unit = methodLogic.callMethod(FuncEntityLivingBaseSetAbsorptionAmount, () => super.setAbsorptionAmount(amount), amount)
    override def setActiveHand(hand: EnumHand): Unit = methodLogic.callMethod(FuncEntityLivingBaseSetActiveHand, () => super.setActiveHand(hand), hand)
    methodLogic.addFinalMethod(FuncEntityLivingBaseSetArrowCountInEntity, (args: Seq[Any]) => super.setArrowCountInEntity(args(0).asInstanceOf[Int]))
    override def setHealth(health: Float): Unit = methodLogic.callMethod(FuncEntityLivingBaseSetHealth, () => super.setHealth(health), health)
    override def setHeldItem(hand: EnumHand, stack: ItemStack): Unit = methodLogic.callMethod(FuncEntityLivingBaseSetHeldItem, () => super.setHeldItem(hand, stack), hand, stack)
    override def setJumping(jumping: Boolean): Unit = methodLogic.callMethod(FuncEntityLivingBaseSetJumping, () => super.setJumping(jumping), jumping)
    override def setLastAttacker(entityIn: Entity): Unit = methodLogic.callMethod(FuncEntityLivingBaseSetLastAttacker, () => super.setLastAttacker(entityIn), entityIn)
    override def setRevengeTarget(livingBase: EntityLivingBase): Unit = methodLogic.callMethod(FuncEntityLivingBaseSetRevengeTarget, () => super.setRevengeTarget(livingBase), livingBase)
    override def stopActiveHand(): Unit = methodLogic.callMethod(FuncEntityLivingBaseStopActiveHand, () => super.stopActiveHand())
    override def swingArm(hand: EnumHand): Unit = methodLogic.callMethod(FuncEntityLivingBaseSwingArm, () => super.swingArm(hand), hand)
    override def teleportTo_(x: Double, y: Double, z: Double): Boolean = methodLogic.callMethod(FuncEntityLivingBaseTeleportTo_, () => super.teleportTo_(x, y, z), x, y, z)
    override def updateAITick(): Unit = methodLogic.callMethod(FuncEntityLivingBaseUpdateAITick, () => super.updateAITick())
    override def updateActiveHand(): Unit = methodLogic.callMethod(FuncEntityLivingBaseUpdateActiveHand, () => super.updateActiveHand())
    override def updateArmSwingProgress(): Unit = methodLogic.callMethod(FuncEntityLivingBaseUpdateArmSwingProgress, () => super.updateArmSwingProgress())
    override def updateDistance(p_110146_1_ : Float, p_110146_2_ : Float): Float = methodLogic.callMethod(FuncEntityLivingBaseUpdateDistance, () => super.updateDistance(p_110146_1_, p_110146_2_), p_110146_1_, p_110146_2_)
    methodLogic.addFinalMethod(FuncEntityLivingBaseUpdateEntityActionState, (args: Seq[Any]) => super.updateEntityActionState())
    override def updateItemUse(stack: ItemStack, eatingParticleCount: Int): Unit = methodLogic.callMethod(FuncEntityLivingBaseUpdateItemUse, () => super.updateItemUse(stack, eatingParticleCount), stack, eatingParticleCount)
    override def updatePotionEffects(): Unit = methodLogic.callMethod(FuncEntityLivingBaseUpdatePotionEffects, () => super.updatePotionEffects())
    override def updatePotionMetadata(): Unit = methodLogic.callMethod(FuncEntityLivingBaseUpdatePotionMetadata, () => super.updatePotionMetadata())


}
