package seremis.geninfusion.api.lib.reflection

import seremis.geninfusion.helper.MCPNames._

/**
  * This is a library class containing all function names used in reflection.
  * The variables in this class will be converted to mcp names in the dev environment
  * by the MCPNames object.
  * The names that don't call the method() function are not used inside minecraft.
  * Functions are named according to the rule: FuncClassNameFunctionName
  */
object FunctionLib {
    final val FuncEntityGetEntityId = field("func_145782_y")
    final val FuncEntitySetEntityId = field("func_145769_d")
    final val FuncEntityEntityInit = field("func_70088_a")
    final val FuncEntityGetDataWatcher = field("func_70096_w")
    final val FuncEntityEquals = "equals"
    final val FuncEntityHashCode = "hashCode"
    final val FuncEntityPreparePlayerToSpawn = field("func_70065_x")
    final val FuncEntitySetDead = field("func_70106_y")
    final val FuncEntitySetSize = field("func_70105_a")
    final val FuncEntitySetRotation = field("func_70101_b")
    final val FuncEntitySetPosition = field("func_70107_b")
    final val FuncEntitySetAngles = field("func_70082_c")
    final val FuncEntityOnUpdate = field("func_70071_h_")
    final val FuncEntityOnEntityUpdate = field("func_70030_z")
    final val FuncEntityGetMaxInPortalTime = field("func_82145_z")
    final val FuncEntitySetOnFireFromLava = field("func_70044_A")
    final val FuncEntitySetFire = field("func_70015_d")
    final val FuncEntityExtinguish = field("func_70066_B")
    final val FuncEntityKill = field("func_70076_C")
    final val FuncEntityIsOffsetPositionInLiquid = field("func_70038_c")
    final val FuncEntityMoveEntity = field("func_70091_d")
    final val FuncEntityGetSwimSound = field("func_145776_H")
    final val FuncEntityDoBlockCollisions = "doBlockCollisions"
    final val FuncEntityPlayStepSound = "playStepSound"
    final val FuncEntityPlaySound = field("func_72704_a")
    final val FuncEntityCanTriggerWalking = field("func_70041_e_")
    final val FuncEntityUpdateFallState = field("func_70064_a")
    final val FuncEntityGetBoundingBox = field("func_70046_E")
    final val FuncEntityDealFireDamage = field("func_70081_e")
    final val FuncEntityIsImmuneToFire = field("func_70045_F") //final method
    final val FuncEntityFall = field("func_70069_a")
    final val FuncEntityIsWet = field("func_70026_G")
    final val FuncEntityIsInWater = field("func_70090_H")
    final val FuncEntityHandleWaterMovement = field("func_70072_I")
    final val FuncEntityGetSplashSound = field("func_145777_O")
    final val FuncEntityIsInsideOfMaterial = field("func_70055_a")
    final val FuncEntityGetEyeHeight = field("func_70047_e")
    final val FuncEntityHandleLavaMovement = field("func_70058_J")
    final val FuncEntityMoveFlying = field("func_70060_a")
    final val FuncEntityGetBrightnessForRender = field("func_70070_b")
    final val FuncEntityGetBrightness = field("func_70013_c")
    final val FuncEntitySetWorld = field("func_70029_a")
    final val FuncEntitySetPositionAndRotation = field("func_70080_a")
    final val FuncEntitySetLocationAndAngles = field("func_70012_b")
    final val FuncEntityGetDistanceToEntity = field("func_70032_d")
    final val FuncEntityGetDistanceSq = field("func_70092_e")
    final val FuncEntityGetDistance = field("func_70011_f")
    final val FuncEntityGetDistanceSqToEntity = field("func_70068_e")
    final val FuncEntityOnCollideWithPlayer = field("func_70100_b_")
    final val FuncEntityApplyEntityCollision = field("func_70108_f")
    final val FuncEntityAddVelocity = field("func_70024_g")
    final val FuncEntitySetBeenAttacked = field("func_70018_K")
    final val FuncEntityAttackEntityFrom = field("func_70097_a")
    final val FuncEntityCanBeCollidedWith = field("func_70067_L")
    final val FuncEntityCanBePushed = field("func_70104_M")
    final val FuncEntityAddToPlayerScore = field("func_70084_c")
    final val FuncEntityIsInRangeToRender3d = field("func_145770_h")
    final val FuncEntityIsInRangeToRenderDist = field("func_70112_a")
    final val FuncEntityWriteMountToNBT = field("func_98035_c")
    final val FuncEntityWriteToNBTOptional = field("func_70039_c")
    final val FuncEntityWriteToNBT = field("func_70109_d")
    final val FuncEntityReadFromNBT = field("func_70020_e")
    final val FuncEntityShouldSetPosAfterLoading = field("func_142008_O")
    final val FuncEntityGetEntityString = field("func_70022_Q") // final method
    final val FuncEntityReadEntityFromNBT = field("func_70037_a")
    final val FuncEntityWriteEntityToNBT = field("func_70014_b")
    final val FuncEntityOnChunkLoad = field("func_76631_c")
    final val FuncEntityNewDoubleNBTList = field("func_70087_a") // obviously library function, not implemented
    final val FuncEntityNewFloatNBTList = field("func_70049_a") // obviously library function, not implemented
    final val FuncEntityDropItem = field("func_145779_a") // library function, not implemented
    final val FuncEntityDropItemWithOffset = "dropItemWithOffset" // library function, no return type
    final val FuncEntityEntityDropItem = field("func_70099_a") // library function, no return type
    final val FuncEntityGetShadowSize = field("func_70053_R")
    final val FuncEntityIsEntityAlive = field("func_70089_S")
    final val FuncEntityIsEntityInsideOpaqueBlock = field("func_70094_T")
    final val FuncEntityInteractFirst = field("func_130002_c") //final
    final val FuncEntityGetCollisionBox = field("func_70114_g")
    final val FuncEntityUpdateRidden = field("func_70098_U")
    final val FuncEntityUpdateRiderPosition = field("func_70043_V")
    final val FuncEntityGetYOffset = field("func_70033_W")
    final val FuncEntityGetMountedYOffset = field("func_70042_X")
    final val FuncEntityMountEntity = field("func_70078_a")
    final val FuncEntitySetPositionAndRotation2 = field("func_70056_a")
    final val FuncEntityGetCollisionBorderSize = field("func_70111_Y")
    final val FuncEntityGetLookVec = field("func_70040_Z")
    final val FuncEntitySetInPortal = field("func_70063_aa")
    final val FuncEntityGetPortalCooldown = field("func_82147_ab")
    final val FuncEntitySetVelocity = field("func_70016_h")
    final val FuncEntityHandleHealthUpdate = field("func_70103_a")
    final val FuncEntityPerformHurtAnimation = field("func_70057_ab")
    final val FuncEntityGetInventory = field("func_75138_a")
    final val FuncEntitySetCurrentItemOrArmor = field("func_70062_b")
    final val FuncEntityIsBurning = field("func_70027_ad")
    final val FuncEntityIsRiding = field("func_70115_ae")
    final val FuncEntityIsSneaking = field("func_70093_af")
    final val FuncEntitySetSneaking = field("func_70095_a")
    final val FuncEntityIsSprinting = field("func_70051_ag")
    final val FuncEntitySetSprinting = field("func_70031_b")
    final val FuncEntityIsInvisible = field("func_82150_aj")
    final val FuncEntityIsInvisibleToPlayer = field("func_98034_c")
    final val FuncEntitySetInvisible = field("func_82142_c")
    final val FuncEntityIsEating = field("func_70113_ah")
    final val FuncEntitySetEating = field("func_70019_c")
    final val FuncEntityGetFlag = field("func_70083_f")
    final val FuncEntitySetFlag = field("func_70052_a")
    final val FuncEntityGetAir = field("func_70086_ai")
    final val FuncEntitySetAir = field("func_70050_g")
    final val FuncEntityOnStruckByLightning = field("func_70077_a")
    final val FuncEntityOnKillEntity = field("func_70074_a")
    final val FuncEntityPushOutOfBlocks = "pushOutOfBlocks"
    final val FuncEntitySetInWeb = field("func_70110_aj")
    final val FuncEntityGetCommandSenderName = field("func_70005_c_")
    final val FuncEntityGetParts = field("func_70021_al")
    final val FuncEntityIsEntityEqual = field("func_70028_i")
    final val FuncEntityGetRotationYawHead = field("func_70079_am")
    final val FuncEntitySetRotationYawHead = field("func_70034_d")
    final val FuncEntityCanAttackWithItem = field("func_70075_an")
    final val FuncEntityHitByEntity = field("func_85031_j")
    final val FuncEntityToString = "toString"
    final val FuncEntityIsEntityInvulnerable = field("func_85032_ar")
    final val FuncEntityCopyLocationAndAnglesFrom = field("func_82149_j")
    final val FuncEntityCopyDataFrom = field("func_82141_a")
    final val FuncEntityTravelToDimension = field("func_71027_c")
    final val FuncEntityGetExplosionResistance = field("func_149638_a")
    final val FuncEntityFunc_145774_a = "func_145774_a"
    final val FuncEntityGetMaxFallHeight = "getMaxFallHeight"
    final val FuncEntityGetTeleportDirection = field("func_82148_at")
    final val FuncEntityDoesEntityNotTriggerPressurePlate = field("func_145773_az")
    final val FuncEntityAddEntityCrashInfo = field("func_85029_a")
    final val FuncEntityCanRenderOnFire = field("func_90999_ad")
    final val FuncEntityGetUniqueID = field("func_80006_f")
    final val FuncEntityIsPushedByWater = field("func_96092_aw")
    final val FuncEntityGetFormattedCommandSenderName = "getFormattedCommandSenderName"
    final val FuncEntityFunc_145781_i = "func_145781_i"
    final val FuncEntityGetEntityData = "getEntityData"
    final val FuncEntityShouldRiderSit = "shouldRiderSit"
    final val FuncEntityGetPickedResult = "getPickedResult"
    final val FuncEntityGetPersistentID = "getPersistentID"
    final val FuncEntityResetEntityId = "resetEntityId" //final
    final val FuncEntityShouldRenderInPass = "shouldRenderInPass"
    final val FuncEntityIsCreatureType = "isCreatureType"
    final val FuncEntityRegisterExtendedProperties = "registerExtendedProperties"
    final val FuncEntityGetExtendedProperties = "getExtendedProperties"
    final val FuncEntityCanRiderInteract = "canRiderInteract"
    final val FuncEntityShouldDismountInWater = "shouldDismountInWater"

    final val FuncIRangedAttackMobAttackEntityWithRangedAttack = field("func_82196_d")
}

